// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.model;

import com.hpe.ao.domain.transaction.Application;
import com.hpe.ao.model.ApplicationSummary;
import java.math.BigDecimal;

privileged aspect ApplicationSummary_Roo_JavaBean {
    
    public Application ApplicationSummary.getApplication() {
        return this.application;
    }
    
    public void ApplicationSummary.setApplication(Application application) {
        this.application = application;
    }
    
    public BigDecimal ApplicationSummary.getApplicationStoryCountBaseline() {
        return this.applicationStoryCountBaseline;
    }
    
    public void ApplicationSummary.setApplicationStoryCountBaseline(BigDecimal applicationStoryCountBaseline) {
        this.applicationStoryCountBaseline = applicationStoryCountBaseline;
    }
    
    public BigDecimal ApplicationSummary.getApplicationStoryPointBaseline() {
        return this.applicationStoryPointBaseline;
    }
    
    public void ApplicationSummary.setApplicationStoryPointBaseline(BigDecimal applicationStoryPointBaseline) {
        this.applicationStoryPointBaseline = applicationStoryPointBaseline;
    }
    
    public BigDecimal ApplicationSummary.getApplicationStoryCountActual() {
        return this.applicationStoryCountActual;
    }
    
    public void ApplicationSummary.setApplicationStoryCountActual(BigDecimal applicationStoryCountActual) {
        this.applicationStoryCountActual = applicationStoryCountActual;
    }
    
    public BigDecimal ApplicationSummary.getApplicationStoryPointActual() {
        return this.applicationStoryPointActual;
    }
    
    public void ApplicationSummary.setApplicationStoryPointActual(BigDecimal applicationStoryPointActual) {
        this.applicationStoryPointActual = applicationStoryPointActual;
    }
    
}
