// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.model;

import com.hpe.ao.domain.transaction.ProjectRelease;
import com.hpe.ao.model.ApplicationSummary;
import com.hpe.ao.model.ReleaseSummary;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

privileged aspect ReleaseSummary_Roo_JavaBean {
    
    public ProjectRelease ReleaseSummary.getProjectRelease() {
        return this.projectRelease;
    }
    
    public void ReleaseSummary.setProjectRelease(ProjectRelease projectRelease) {
        this.projectRelease = projectRelease;
    }
    
    public List<ApplicationSummary> ReleaseSummary.getApplicationSummaryList() {
        return this.applicationSummaryList;
    }
    
    public void ReleaseSummary.setApplicationSummaryList(List<ApplicationSummary> applicationSummaryList) {
        this.applicationSummaryList = applicationSummaryList;
    }
    
    public BigDecimal ReleaseSummary.getReleaseStoryCountBaseline() {
        return this.releaseStoryCountBaseline;
    }
    
    public void ReleaseSummary.setReleaseStoryCountBaseline(BigDecimal releaseStoryCountBaseline) {
        this.releaseStoryCountBaseline = releaseStoryCountBaseline;
    }
    
    public BigDecimal ReleaseSummary.getReleaseStoryPointBaseline() {
        return this.releaseStoryPointBaseline;
    }
    
    public void ReleaseSummary.setReleaseStoryPointBaseline(BigDecimal releaseStoryPointBaseline) {
        this.releaseStoryPointBaseline = releaseStoryPointBaseline;
    }
    
    public Date ReleaseSummary.getStartDateSITBaseline() {
        return this.startDateSITBaseline;
    }
    
    public void ReleaseSummary.setStartDateSITBaseline(Date startDateSITBaseline) {
        this.startDateSITBaseline = startDateSITBaseline;
    }
    
    public Date ReleaseSummary.getStartDateUATBaseline() {
        return this.startDateUATBaseline;
    }
    
    public void ReleaseSummary.setStartDateUATBaseline(Date startDateUATBaseline) {
        this.startDateUATBaseline = startDateUATBaseline;
    }
    
    public Date ReleaseSummary.getStartDateIMPBaseline() {
        return this.startDateIMPBaseline;
    }
    
    public void ReleaseSummary.setStartDateIMPBaseline(Date startDateIMPBaseline) {
        this.startDateIMPBaseline = startDateIMPBaseline;
    }
    
    public BigDecimal ReleaseSummary.getContingencyBaseline() {
        return this.contingencyBaseline;
    }
    
    public void ReleaseSummary.setContingencyBaseline(BigDecimal contingencyBaseline) {
        this.contingencyBaseline = contingencyBaseline;
    }
    
    public BigDecimal ReleaseSummary.getReleaseStoryCountActual() {
        return this.releaseStoryCountActual;
    }
    
    public void ReleaseSummary.setReleaseStoryCountActual(BigDecimal releaseStoryCountActual) {
        this.releaseStoryCountActual = releaseStoryCountActual;
    }
    
    public BigDecimal ReleaseSummary.getReleaseStoryPointActual() {
        return this.releaseStoryPointActual;
    }
    
    public void ReleaseSummary.setReleaseStoryPointActual(BigDecimal releaseStoryPointActual) {
        this.releaseStoryPointActual = releaseStoryPointActual;
    }
    
    public Date ReleaseSummary.getStartDateSITActual() {
        return this.startDateSITActual;
    }
    
    public void ReleaseSummary.setStartDateSITActual(Date startDateSITActual) {
        this.startDateSITActual = startDateSITActual;
    }
    
    public Date ReleaseSummary.getStartDateUATActual() {
        return this.startDateUATActual;
    }
    
    public void ReleaseSummary.setStartDateUATActual(Date startDateUATActual) {
        this.startDateUATActual = startDateUATActual;
    }
    
    public Date ReleaseSummary.getStartDateIMPActual() {
        return this.startDateIMPActual;
    }
    
    public void ReleaseSummary.setStartDateIMPActual(Date startDateIMPActual) {
        this.startDateIMPActual = startDateIMPActual;
    }
    
    public BigDecimal ReleaseSummary.getContingencyActual() {
        return this.contingencyActual;
    }
    
    public void ReleaseSummary.setContingencyActual(BigDecimal contingencyActual) {
        this.contingencyActual = contingencyActual;
    }
    
}
