// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.Application;
import com.hpe.ao.domain.transaction.Project;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;

privileged aspect Application_Roo_Finder {
    
    public static Long Application.countFindApplicationsByProject(Project project) {
        if (project == null) throw new IllegalArgumentException("The project argument is required");
        EntityManager em = Application.entityManager();
        TypedQuery q = em.createQuery("SELECT COUNT(o) FROM Application AS o WHERE o.project = :project", Long.class);
        q.setParameter("project", project);
        return ((Long) q.getSingleResult());
    }
    
    public static TypedQuery<Application> Application.findApplicationsByProject(Project project) {
        if (project == null) throw new IllegalArgumentException("The project argument is required");
        EntityManager em = Application.entityManager();
        TypedQuery<Application> q = em.createQuery("SELECT o FROM Application AS o WHERE o.project = :project", Application.class);
        q.setParameter("project", project);
        return q;
    }
    
    public static TypedQuery<Application> Application.findApplicationsByProject(Project project, String sortFieldName, String sortOrder) {
        if (project == null) throw new IllegalArgumentException("The project argument is required");
        EntityManager em = Application.entityManager();
        StringBuilder queryBuilder = new StringBuilder("SELECT o FROM Application AS o WHERE o.project = :project");
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            queryBuilder.append(" ORDER BY ").append(sortFieldName);
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                queryBuilder.append(" ").append(sortOrder);
            }
        }
        TypedQuery<Application> q = em.createQuery(queryBuilder.toString(), Application.class);
        q.setParameter("project", project);
        return q;
    }
    
}
