// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.Application;
import com.hpe.ao.domain.transaction.Project;
import java.math.BigDecimal;

privileged aspect Application_Roo_JavaBean {
    
    public String Application.getLeadName() {
        return this.leadName;
    }
    
    public void Application.setLeadName(String leadName) {
        this.leadName = leadName;
    }
    
    public Project Application.getProject() {
        return this.project;
    }
    
    public void Application.setProject(Project project) {
        this.project = project;
    }
    
    public BigDecimal Application.getPriority() {
        return this.priority;
    }
    
    public void Application.setPriority(BigDecimal priority) {
        this.priority = priority;
    }
    
    public BigDecimal Application.getStoryCountBaseline() {
        return this.storyCountBaseline;
    }
    
    public void Application.setStoryCountBaseline(BigDecimal storyCountBaseline) {
        this.storyCountBaseline = storyCountBaseline;
    }
    
    public BigDecimal Application.getStoryPointBaseline() {
        return this.storyPointBaseline;
    }
    
    public void Application.setStoryPointBaseline(BigDecimal storyPointBaseline) {
        this.storyPointBaseline = storyPointBaseline;
    }
    
    public BigDecimal Application.getStoryCountActual() {
        return this.storyCountActual;
    }
    
    public void Application.setStoryCountActual(BigDecimal storyCountActual) {
        this.storyCountActual = storyCountActual;
    }
    
    public BigDecimal Application.getStoryPointActual() {
        return this.storyPointActual;
    }
    
    public void Application.setStoryPointActual(BigDecimal storyPointActual) {
        this.storyPointActual = storyPointActual;
    }
    
}
