// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.Capacity;
import com.hpe.ao.domain.transaction.Project;
import java.math.BigDecimal;

privileged aspect Capacity_Roo_JavaBean {
    
    public Project Capacity.getProject() {
        return this.project;
    }
    
    public void Capacity.setProject(Project project) {
        this.project = project;
    }
    
    public BigDecimal Capacity.getTeamCountBaseline() {
        return this.teamCountBaseline;
    }
    
    public void Capacity.setTeamCountBaseline(BigDecimal teamCountBaseline) {
        this.teamCountBaseline = teamCountBaseline;
    }
    
    public BigDecimal Capacity.getTeamSizeBaseline() {
        return this.teamSizeBaseline;
    }
    
    public void Capacity.setTeamSizeBaseline(BigDecimal teamSizeBaseline) {
        this.teamSizeBaseline = teamSizeBaseline;
    }
    
    public BigDecimal Capacity.getTeamAvailabilityBaseline() {
        return this.teamAvailabilityBaseline;
    }
    
    public void Capacity.setTeamAvailabilityBaseline(BigDecimal teamAvailabilityBaseline) {
        this.teamAvailabilityBaseline = teamAvailabilityBaseline;
    }
    
    public BigDecimal Capacity.getTeamAveragePointDailyBaseline() {
        return this.teamAveragePointDailyBaseline;
    }
    
    public void Capacity.setTeamAveragePointDailyBaseline(BigDecimal teamAveragePointDailyBaseline) {
        this.teamAveragePointDailyBaseline = teamAveragePointDailyBaseline;
    }
    
    public BigDecimal Capacity.getPointCapacityBaseline() {
        return this.pointCapacityBaseline;
    }
    
    public void Capacity.setPointCapacityBaseline(BigDecimal pointCapacityBaseline) {
        this.pointCapacityBaseline = pointCapacityBaseline;
    }
    
    public BigDecimal Capacity.getTeamCountActual() {
        return this.teamCountActual;
    }
    
    public void Capacity.setTeamCountActual(BigDecimal teamCountActual) {
        this.teamCountActual = teamCountActual;
    }
    
    public BigDecimal Capacity.getTeamSizeActual() {
        return this.teamSizeActual;
    }
    
    public void Capacity.setTeamSizeActual(BigDecimal teamSizeActual) {
        this.teamSizeActual = teamSizeActual;
    }
    
    public BigDecimal Capacity.getTeamAvailabilityActual() {
        return this.teamAvailabilityActual;
    }
    
    public void Capacity.setTeamAvailabilityActual(BigDecimal teamAvailabilityActual) {
        this.teamAvailabilityActual = teamAvailabilityActual;
    }
    
    public BigDecimal Capacity.getTeamAveragePointDailyActual() {
        return this.teamAveragePointDailyActual;
    }
    
    public void Capacity.setTeamAveragePointDailyActual(BigDecimal teamAveragePointDailyActual) {
        this.teamAveragePointDailyActual = teamAveragePointDailyActual;
    }
    
    public BigDecimal Capacity.getPointCapacityActual() {
        return this.pointCapacityActual;
    }
    
    public void Capacity.setPointCapacityActual(BigDecimal pointCapacityActual) {
        this.pointCapacityActual = pointCapacityActual;
    }
    
    public BigDecimal Capacity.getFactor1() {
        return this.factor1;
    }
    
    public void Capacity.setFactor1(BigDecimal factor1) {
        this.factor1 = factor1;
    }
    
    public String Capacity.getFactor1Description() {
        return this.factor1Description;
    }
    
    public void Capacity.setFactor1Description(String factor1Description) {
        this.factor1Description = factor1Description;
    }
    
    public BigDecimal Capacity.getFactor2() {
        return this.factor2;
    }
    
    public void Capacity.setFactor2(BigDecimal factor2) {
        this.factor2 = factor2;
    }
    
    public String Capacity.getFactor2Description() {
        return this.factor2Description;
    }
    
    public void Capacity.setFactor2Description(String factor2Description) {
        this.factor2Description = factor2Description;
    }
    
    public BigDecimal Capacity.getFactor3() {
        return this.factor3;
    }
    
    public void Capacity.setFactor3(BigDecimal factor3) {
        this.factor3 = factor3;
    }
    
    public String Capacity.getFactor3Description() {
        return this.factor3Description;
    }
    
    public void Capacity.setFactor3Description(String factor3Description) {
        this.factor3Description = factor3Description;
    }
    
}
