// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.Capacity;
import java.util.List;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Capacity_Roo_Jpa_ActiveRecord {
    
    public static final List<String> Capacity.fieldNames4OrderClauseFilter = java.util.Arrays.asList("project", "teamCountBaseline", "teamSizeBaseline", "teamAvailabilityBaseline", "teamAveragePointDailyBaseline", "pointCapacityBaseline", "teamCountActual", "teamSizeActual", "teamAvailabilityActual", "teamAveragePointDailyActual", "pointCapacityActual", "factor1", "factor1Description", "factor2", "factor2Description", "factor3", "factor3Description");
    
    public static long Capacity.countCapacitys() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Capacity o", Long.class).getSingleResult();
    }
    
    public static List<Capacity> Capacity.findAllCapacitys() {
        return entityManager().createQuery("SELECT o FROM Capacity o", Capacity.class).getResultList();
    }
    
    public static List<Capacity> Capacity.findAllCapacitys(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Capacity o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Capacity.class).getResultList();
    }
    
    public static Capacity Capacity.findCapacity(Long id) {
        if (id == null) return null;
        return entityManager().find(Capacity.class, id);
    }
    
    public static List<Capacity> Capacity.findCapacityEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Capacity o", Capacity.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<Capacity> Capacity.findCapacityEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Capacity o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Capacity.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public Capacity Capacity.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Capacity merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
