// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.Feature;
import java.util.List;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Feature_Roo_Jpa_ActiveRecord {
    
    public static final List<String> Feature.fieldNames4OrderClauseFilter = java.util.Arrays.asList("leadName", "application", "projectRelease", "storyCountBaseline", "storyPointBaseline", "storyCountActual", "storyPointActual");
    
    public static long Feature.countFeatures() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Feature o", Long.class).getSingleResult();
    }
    
    public static List<Feature> Feature.findAllFeatures() {
        return entityManager().createQuery("SELECT o FROM Feature o", Feature.class).getResultList();
    }
    
    public static List<Feature> Feature.findAllFeatures(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Feature o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Feature.class).getResultList();
    }
    
    public static Feature Feature.findFeature(Long id) {
        if (id == null) return null;
        return entityManager().find(Feature.class, id);
    }
    
    public static List<Feature> Feature.findFeatureEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Feature o", Feature.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<Feature> Feature.findFeatureEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Feature o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Feature.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public Feature Feature.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Feature merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
