// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.Feature;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect Feature_Roo_Jpa_Entity {
    
    declare @type: Feature: @Entity;
    
    declare @type: Feature: @Table(name = "T2_FTR");
    
}
