// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.Application;
import com.hpe.ao.domain.transaction.Feature;
import com.hpe.ao.domain.transaction.ProjectRelease;
import java.math.BigDecimal;

privileged aspect Feature_Roo_JavaBean {
    
    public String Feature.getLeadName() {
        return this.leadName;
    }
    
    public void Feature.setLeadName(String leadName) {
        this.leadName = leadName;
    }
    
    public Application Feature.getApplication() {
        return this.application;
    }
    
    public void Feature.setApplication(Application application) {
        this.application = application;
    }
    
    public ProjectRelease Feature.getProjectRelease() {
        return this.projectRelease;
    }
    
    public void Feature.setProjectRelease(ProjectRelease projectRelease) {
        this.projectRelease = projectRelease;
    }
    
    public BigDecimal Feature.getStoryCountBaseline() {
        return this.storyCountBaseline;
    }
    
    public void Feature.setStoryCountBaseline(BigDecimal storyCountBaseline) {
        this.storyCountBaseline = storyCountBaseline;
    }
    
    public BigDecimal Feature.getStoryPointBaseline() {
        return this.storyPointBaseline;
    }
    
    public void Feature.setStoryPointBaseline(BigDecimal storyPointBaseline) {
        this.storyPointBaseline = storyPointBaseline;
    }
    
    public BigDecimal Feature.getStoryCountActual() {
        return this.storyCountActual;
    }
    
    public void Feature.setStoryCountActual(BigDecimal storyCountActual) {
        this.storyCountActual = storyCountActual;
    }
    
    public BigDecimal Feature.getStoryPointActual() {
        return this.storyPointActual;
    }
    
    public void Feature.setStoryPointActual(BigDecimal storyPointActual) {
        this.storyPointActual = storyPointActual;
    }
    
}
