// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.PrgPrjInitSetup;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect PrgPrjInitSetup_Roo_JavaBean {
    
    public String PrgPrjInitSetup.getProgram1() {
        return this.program1;
    }
    
    public void PrgPrjInitSetup.setProgram1(String program1) {
        this.program1 = program1;
    }
    
    public String PrgPrjInitSetup.getOrgName() {
        return this.orgName;
    }
    
    public void PrgPrjInitSetup.setOrgName(String orgName) {
        this.orgName = orgName;
    }
    
    public Date PrgPrjInitSetup.getStartDateBaseline() {
        return this.startDateBaseline;
    }
    
    public void PrgPrjInitSetup.setStartDateBaseline(Date startDateBaseline) {
        this.startDateBaseline = startDateBaseline;
    }
    
    public String PrgPrjInitSetup.getProject11() {
        return this.project11;
    }
    
    public void PrgPrjInitSetup.setProject11(String project11) {
        this.project11 = project11;
    }
    
    public BigDecimal PrgPrjInitSetup.getProject11TeamCount() {
        return this.project11TeamCount;
    }
    
    public void PrgPrjInitSetup.setProject11TeamCount(BigDecimal project11TeamCount) {
        this.project11TeamCount = project11TeamCount;
    }
    
    public BigDecimal PrgPrjInitSetup.getProject11TeamSize() {
        return this.project11TeamSize;
    }
    
    public void PrgPrjInitSetup.setProject11TeamSize(BigDecimal project11TeamSize) {
        this.project11TeamSize = project11TeamSize;
    }
    
    public BigDecimal PrgPrjInitSetup.getProject11TeamAveragePointDaily() {
        return this.project11TeamAveragePointDaily;
    }
    
    public void PrgPrjInitSetup.setProject11TeamAveragePointDaily(BigDecimal project11TeamAveragePointDaily) {
        this.project11TeamAveragePointDaily = project11TeamAveragePointDaily;
    }
    
    public String PrgPrjInitSetup.getRelease111() {
        return this.release111;
    }
    
    public void PrgPrjInitSetup.setRelease111(String release111) {
        this.release111 = release111;
    }
    
    public String PrgPrjInitSetup.getProject12() {
        return this.project12;
    }
    
    public void PrgPrjInitSetup.setProject12(String project12) {
        this.project12 = project12;
    }
    
    public BigDecimal PrgPrjInitSetup.getProject12TeamCount() {
        return this.project12TeamCount;
    }
    
    public void PrgPrjInitSetup.setProject12TeamCount(BigDecimal project12TeamCount) {
        this.project12TeamCount = project12TeamCount;
    }
    
    public BigDecimal PrgPrjInitSetup.getProject12TeamSize() {
        return this.project12TeamSize;
    }
    
    public void PrgPrjInitSetup.setProject12TeamSize(BigDecimal project12TeamSize) {
        this.project12TeamSize = project12TeamSize;
    }
    
    public BigDecimal PrgPrjInitSetup.getProject12TeamAveragePointDaily() {
        return this.project12TeamAveragePointDaily;
    }
    
    public void PrgPrjInitSetup.setProject12TeamAveragePointDaily(BigDecimal project12TeamAveragePointDaily) {
        this.project12TeamAveragePointDaily = project12TeamAveragePointDaily;
    }
    
    public String PrgPrjInitSetup.getRelease121() {
        return this.release121;
    }
    
    public void PrgPrjInitSetup.setRelease121(String release121) {
        this.release121 = release121;
    }
    
    public String PrgPrjInitSetup.getProject13() {
        return this.project13;
    }
    
    public void PrgPrjInitSetup.setProject13(String project13) {
        this.project13 = project13;
    }
    
    public BigDecimal PrgPrjInitSetup.getProject13TeamCount() {
        return this.project13TeamCount;
    }
    
    public void PrgPrjInitSetup.setProject13TeamCount(BigDecimal project13TeamCount) {
        this.project13TeamCount = project13TeamCount;
    }
    
    public BigDecimal PrgPrjInitSetup.getProject13TeamSize() {
        return this.project13TeamSize;
    }
    
    public void PrgPrjInitSetup.setProject13TeamSize(BigDecimal project13TeamSize) {
        this.project13TeamSize = project13TeamSize;
    }
    
    public BigDecimal PrgPrjInitSetup.getProject13TeamAveragePointDaily() {
        return this.project13TeamAveragePointDaily;
    }
    
    public void PrgPrjInitSetup.setProject13TeamAveragePointDaily(BigDecimal project13TeamAveragePointDaily) {
        this.project13TeamAveragePointDaily = project13TeamAveragePointDaily;
    }
    
    public String PrgPrjInitSetup.getRelease131() {
        return this.release131;
    }
    
    public void PrgPrjInitSetup.setRelease131(String release131) {
        this.release131 = release131;
    }
    
    public String PrgPrjInitSetup.getApplication111() {
        return this.application111;
    }
    
    public void PrgPrjInitSetup.setApplication111(String application111) {
        this.application111 = application111;
    }
    
    public String PrgPrjInitSetup.getApplication112() {
        return this.application112;
    }
    
    public void PrgPrjInitSetup.setApplication112(String application112) {
        this.application112 = application112;
    }
    
    public String PrgPrjInitSetup.getApplication113() {
        return this.application113;
    }
    
    public void PrgPrjInitSetup.setApplication113(String application113) {
        this.application113 = application113;
    }
    
    public String PrgPrjInitSetup.getApplication114() {
        return this.application114;
    }
    
    public void PrgPrjInitSetup.setApplication114(String application114) {
        this.application114 = application114;
    }
    
    public String PrgPrjInitSetup.getApplication121() {
        return this.application121;
    }
    
    public void PrgPrjInitSetup.setApplication121(String application121) {
        this.application121 = application121;
    }
    
    public String PrgPrjInitSetup.getApplication122() {
        return this.application122;
    }
    
    public void PrgPrjInitSetup.setApplication122(String application122) {
        this.application122 = application122;
    }
    
    public String PrgPrjInitSetup.getApplication123() {
        return this.application123;
    }
    
    public void PrgPrjInitSetup.setApplication123(String application123) {
        this.application123 = application123;
    }
    
    public String PrgPrjInitSetup.getApplication124() {
        return this.application124;
    }
    
    public void PrgPrjInitSetup.setApplication124(String application124) {
        this.application124 = application124;
    }
    
    public String PrgPrjInitSetup.getApplication131() {
        return this.application131;
    }
    
    public void PrgPrjInitSetup.setApplication131(String application131) {
        this.application131 = application131;
    }
    
    public String PrgPrjInitSetup.getApplication132() {
        return this.application132;
    }
    
    public void PrgPrjInitSetup.setApplication132(String application132) {
        this.application132 = application132;
    }
    
    public String PrgPrjInitSetup.getApplication133() {
        return this.application133;
    }
    
    public void PrgPrjInitSetup.setApplication133(String application133) {
        this.application133 = application133;
    }
    
    public String PrgPrjInitSetup.getApplication134() {
        return this.application134;
    }
    
    public void PrgPrjInitSetup.setApplication134(String application134) {
        this.application134 = application134;
    }
    
}
