// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.PrgPrjInitSetup;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect PrgPrjInitSetup_Roo_Jpa_Entity {
    
    declare @type: PrgPrjInitSetup: @Entity;
    
    declare @type: PrgPrjInitSetup: @Table(name = "T3_PRG_PRJ_INIT_SETUP");
    
}
