// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.PrgPrjSelectMenu;
import com.hpe.ao.domain.transaction.Program;
import com.hpe.ao.domain.transaction.Project;

privileged aspect PrgPrjSelectMenu_Roo_JavaBean {
    
    public String PrgPrjSelectMenu.getCreateUser() {
        return this.createUser;
    }
    
    public void PrgPrjSelectMenu.setCreateUser(String createUser) {
        this.createUser = createUser;
    }
    
    public Program PrgPrjSelectMenu.getProgram() {
        return this.program;
    }
    
    public void PrgPrjSelectMenu.setProgram(Program program) {
        this.program = program;
    }
    
    public Project PrgPrjSelectMenu.getProject() {
        return this.project;
    }
    
    public void PrgPrjSelectMenu.setProject(Project project) {
        this.project = project;
    }
    
}
