// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.PrgPrjSelectMenu;
import java.util.List;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PrgPrjSelectMenu_Roo_Jpa_ActiveRecord {
    
    public static final List<String> PrgPrjSelectMenu.fieldNames4OrderClauseFilter = java.util.Arrays.asList("createUser", "program", "project");
    
    public static long PrgPrjSelectMenu.countPrgPrjSelectMenus() {
        return entityManager().createQuery("SELECT COUNT(o) FROM PrgPrjSelectMenu o", Long.class).getSingleResult();
    }
    
    public static List<PrgPrjSelectMenu> PrgPrjSelectMenu.findAllPrgPrjSelectMenus() {
        return entityManager().createQuery("SELECT o FROM PrgPrjSelectMenu o", PrgPrjSelectMenu.class).getResultList();
    }
    
    public static List<PrgPrjSelectMenu> PrgPrjSelectMenu.findAllPrgPrjSelectMenus(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM PrgPrjSelectMenu o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, PrgPrjSelectMenu.class).getResultList();
    }
    
    public static PrgPrjSelectMenu PrgPrjSelectMenu.findPrgPrjSelectMenu(Long id) {
        if (id == null) return null;
        return entityManager().find(PrgPrjSelectMenu.class, id);
    }
    
    public static List<PrgPrjSelectMenu> PrgPrjSelectMenu.findPrgPrjSelectMenuEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM PrgPrjSelectMenu o", PrgPrjSelectMenu.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<PrgPrjSelectMenu> PrgPrjSelectMenu.findPrgPrjSelectMenuEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM PrgPrjSelectMenu o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, PrgPrjSelectMenu.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public PrgPrjSelectMenu PrgPrjSelectMenu.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        PrgPrjSelectMenu merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
