// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.Program;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect Program_Roo_Jpa_Entity {
    
    declare @type: Program: @Entity;
    
    declare @type: Program: @Table(name = "T2_PRG");
    
}
