// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.ProgressEntry;
import java.util.List;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProgressEntry_Roo_Jpa_ActiveRecord {
    
    public static final List<String> ProgressEntry.fieldNames4OrderClauseFilter = java.util.Arrays.asList("project", "feature", "storyCountComplete", "storyPointComplete");
    
    public static long ProgressEntry.countProgressEntrys() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ProgressEntry o", Long.class).getSingleResult();
    }
    
    public static List<ProgressEntry> ProgressEntry.findAllProgressEntrys() {
        return entityManager().createQuery("SELECT o FROM ProgressEntry o", ProgressEntry.class).getResultList();
    }
    
    public static List<ProgressEntry> ProgressEntry.findAllProgressEntrys(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM ProgressEntry o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, ProgressEntry.class).getResultList();
    }
    
    public static ProgressEntry ProgressEntry.findProgressEntry(Long id) {
        if (id == null) return null;
        return entityManager().find(ProgressEntry.class, id);
    }
    
    public static List<ProgressEntry> ProgressEntry.findProgressEntryEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ProgressEntry o", ProgressEntry.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<ProgressEntry> ProgressEntry.findProgressEntryEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM ProgressEntry o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, ProgressEntry.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public ProgressEntry ProgressEntry.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ProgressEntry merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
