// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.Program;

privileged aspect Program_Roo_JavaBean {
    
    public String Program.getOrgName() {
        return this.orgName;
    }
    
    public void Program.setOrgName(String orgName) {
        this.orgName = orgName;
    }
    
}
