// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.Feature;
import com.hpe.ao.domain.transaction.ProgressEntry;
import com.hpe.ao.domain.transaction.Project;
import java.math.BigDecimal;

privileged aspect ProgressEntry_Roo_JavaBean {
    
    public Project ProgressEntry.getProject() {
        return this.project;
    }
    
    public void ProgressEntry.setProject(Project project) {
        this.project = project;
    }
    
    public Feature ProgressEntry.getFeature() {
        return this.feature;
    }
    
    public void ProgressEntry.setFeature(Feature feature) {
        this.feature = feature;
    }
    
    public BigDecimal ProgressEntry.getStoryCountComplete() {
        return this.storyCountComplete;
    }
    
    public void ProgressEntry.setStoryCountComplete(BigDecimal storyCountComplete) {
        this.storyCountComplete = storyCountComplete;
    }
    
    public BigDecimal ProgressEntry.getStoryPointComplete() {
        return this.storyPointComplete;
    }
    
    public void ProgressEntry.setStoryPointComplete(BigDecimal storyPointComplete) {
        this.storyPointComplete = storyPointComplete;
    }
    
}
