// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.Project;
import com.hpe.ao.domain.transaction.ProjectRelease;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect ProjectRelease_Roo_JavaBean {
    
    public String ProjectRelease.getLeadName() {
        return this.leadName;
    }
    
    public void ProjectRelease.setLeadName(String leadName) {
        this.leadName = leadName;
    }
    
    public Project ProjectRelease.getProject() {
        return this.project;
    }
    
    public void ProjectRelease.setProject(Project project) {
        this.project = project;
    }
    
    public BigDecimal ProjectRelease.getDurationSITBaseline() {
        return this.durationSITBaseline;
    }
    
    public void ProjectRelease.setDurationSITBaseline(BigDecimal durationSITBaseline) {
        this.durationSITBaseline = durationSITBaseline;
    }
    
    public BigDecimal ProjectRelease.getDurationUATBaseline() {
        return this.durationUATBaseline;
    }
    
    public void ProjectRelease.setDurationUATBaseline(BigDecimal durationUATBaseline) {
        this.durationUATBaseline = durationUATBaseline;
    }
    
    public BigDecimal ProjectRelease.getDurationIMPBaseline() {
        return this.durationIMPBaseline;
    }
    
    public void ProjectRelease.setDurationIMPBaseline(BigDecimal durationIMPBaseline) {
        this.durationIMPBaseline = durationIMPBaseline;
    }
    
    public Date ProjectRelease.getGoLiveDateBaseline() {
        return this.goLiveDateBaseline;
    }
    
    public void ProjectRelease.setGoLiveDateBaseline(Date goLiveDateBaseline) {
        this.goLiveDateBaseline = goLiveDateBaseline;
    }
    
    public BigDecimal ProjectRelease.getDurationSITActual() {
        return this.durationSITActual;
    }
    
    public void ProjectRelease.setDurationSITActual(BigDecimal durationSITActual) {
        this.durationSITActual = durationSITActual;
    }
    
    public BigDecimal ProjectRelease.getDurationUATActual() {
        return this.durationUATActual;
    }
    
    public void ProjectRelease.setDurationUATActual(BigDecimal durationUATActual) {
        this.durationUATActual = durationUATActual;
    }
    
    public BigDecimal ProjectRelease.getDurationIMPActual() {
        return this.durationIMPActual;
    }
    
    public void ProjectRelease.setDurationIMPActual(BigDecimal durationIMPActual) {
        this.durationIMPActual = durationIMPActual;
    }
    
    public Date ProjectRelease.getGoLiveDateActual() {
        return this.goLiveDateActual;
    }
    
    public void ProjectRelease.setGoLiveDateActual(Date goLiveDateActual) {
        this.goLiveDateActual = goLiveDateActual;
    }
    
}
