// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.ProjectRelease;
import java.util.List;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProjectRelease_Roo_Jpa_ActiveRecord {
    
    public static final List<String> ProjectRelease.fieldNames4OrderClauseFilter = java.util.Arrays.asList("leadName", "project", "durationSITBaseline", "durationUATBaseline", "durationIMPBaseline", "goLiveDateBaseline", "durationSITActual", "durationUATActual", "durationIMPActual", "goLiveDateActual", "availableCapacity");
    
    public static long ProjectRelease.countProjectReleases() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ProjectRelease o", Long.class).getSingleResult();
    }
    
    public static List<ProjectRelease> ProjectRelease.findAllProjectReleases() {
        return entityManager().createQuery("SELECT o FROM ProjectRelease o", ProjectRelease.class).getResultList();
    }
    
    public static List<ProjectRelease> ProjectRelease.findAllProjectReleases(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM ProjectRelease o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, ProjectRelease.class).getResultList();
    }
    
    public static ProjectRelease ProjectRelease.findProjectRelease(Long id) {
        if (id == null) return null;
        return entityManager().find(ProjectRelease.class, id);
    }
    
    public static List<ProjectRelease> ProjectRelease.findProjectReleaseEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ProjectRelease o", ProjectRelease.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<ProjectRelease> ProjectRelease.findProjectReleaseEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM ProjectRelease o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, ProjectRelease.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public ProjectRelease ProjectRelease.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ProjectRelease merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
