// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.Program;
import com.hpe.ao.domain.transaction.Project;
import java.math.BigDecimal;

privileged aspect Project_Roo_JavaBean {
    
    public String Project.getLeadName() {
        return this.leadName;
    }
    
    public void Project.setLeadName(String leadName) {
        this.leadName = leadName;
    }
    
    public Program Project.getProgram() {
        return this.program;
    }
    
    public void Project.setProgram(Program program) {
        this.program = program;
    }
    
    public BigDecimal Project.getTeamAveragePointDaily() {
        return this.teamAveragePointDaily;
    }
    
    public void Project.setTeamAveragePointDaily(BigDecimal teamAveragePointDaily) {
        this.teamAveragePointDaily = teamAveragePointDaily;
    }
    
    public BigDecimal Project.getAveragePointsPerStory() {
        return this.averagePointsPerStory;
    }
    
    public void Project.setAveragePointsPerStory(BigDecimal averagePointsPerStory) {
        this.averagePointsPerStory = averagePointsPerStory;
    }
    
    public BigDecimal Project.getAverageTeamCount() {
        return this.averageTeamCount;
    }
    
    public void Project.setAverageTeamCount(BigDecimal averageTeamCount) {
        this.averageTeamCount = averageTeamCount;
    }
    
    public BigDecimal Project.getAverageTeamSize() {
        return this.averageTeamSize;
    }
    
    public void Project.setAverageTeamSize(BigDecimal averageTeamSize) {
        this.averageTeamSize = averageTeamSize;
    }
    
}
