// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.ApplicationDataOnDemand;
import com.hpe.ao.domain.transaction.ApplicationIntegrationTest;
import com.hpe.ao.service.ApplicationService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ApplicationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ApplicationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ApplicationIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ApplicationIntegrationTest: @Transactional;
    
    @Autowired
    ApplicationDataOnDemand ApplicationIntegrationTest.dod;
    
    @Autowired
    ApplicationService ApplicationIntegrationTest.applicationService;
    
    @Test
    public void ApplicationIntegrationTest.testCountAllApplications() {
        Assert.assertNotNull("Data on demand for 'Application' failed to initialize correctly", dod.getRandomApplication());
        long count = applicationService.countAllApplications();
        Assert.assertTrue("Counter for 'Application' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ApplicationIntegrationTest.testFindApplication() {
        Application obj = dod.getRandomApplication();
        Assert.assertNotNull("Data on demand for 'Application' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Application' failed to provide an identifier", id);
        obj = applicationService.findApplication(id);
        Assert.assertNotNull("Find method for 'Application' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Application' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ApplicationIntegrationTest.testFindAllApplications() {
        Assert.assertNotNull("Data on demand for 'Application' failed to initialize correctly", dod.getRandomApplication());
        long count = applicationService.countAllApplications();
        Assert.assertTrue("Too expensive to perform a find all test for 'Application', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Application> result = applicationService.findAllApplications();
        Assert.assertNotNull("Find all method for 'Application' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Application' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ApplicationIntegrationTest.testFindApplicationEntries() {
        Assert.assertNotNull("Data on demand for 'Application' failed to initialize correctly", dod.getRandomApplication());
        long count = applicationService.countAllApplications();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Application> result = applicationService.findApplicationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Application' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Application' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ApplicationIntegrationTest.testFlush() {
        Application obj = dod.getRandomApplication();
        Assert.assertNotNull("Data on demand for 'Application' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Application' failed to provide an identifier", id);
        obj = applicationService.findApplication(id);
        Assert.assertNotNull("Find method for 'Application' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyApplication(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Application' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ApplicationIntegrationTest.testUpdateApplicationUpdate() {
        Application obj = dod.getRandomApplication();
        Assert.assertNotNull("Data on demand for 'Application' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Application' failed to provide an identifier", id);
        obj = applicationService.findApplication(id);
        boolean modified =  dod.modifyApplication(obj);
        Integer currentVersion = obj.getVersion();
        Application merged = (Application)applicationService.updateApplication(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Application' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ApplicationIntegrationTest.testSaveApplication() {
        Assert.assertNotNull("Data on demand for 'Application' failed to initialize correctly", dod.getRandomApplication());
        Application obj = dod.getNewTransientApplication(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Application' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Application' identifier to be null", obj.getId());
        try {
            applicationService.saveApplication(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Application' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ApplicationIntegrationTest.testDeleteApplication() {
        Application obj = dod.getRandomApplication();
        Assert.assertNotNull("Data on demand for 'Application' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Application' failed to provide an identifier", id);
        obj = applicationService.findApplication(id);
        applicationService.deleteApplication(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Application' with identifier '" + id + "'", applicationService.findApplication(id));
    }
    
}
