// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.CapacityDataOnDemand;
import com.hpe.ao.domain.transaction.CapacityIntegrationTest;
import com.hpe.ao.service.CapacityService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CapacityIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CapacityIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CapacityIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CapacityIntegrationTest: @Transactional;
    
    @Autowired
    CapacityDataOnDemand CapacityIntegrationTest.dod;
    
    @Autowired
    CapacityService CapacityIntegrationTest.capacityService;
    
    @Test
    public void CapacityIntegrationTest.testCountAllCapacitys() {
        Assert.assertNotNull("Data on demand for 'Capacity' failed to initialize correctly", dod.getRandomCapacity());
        long count = capacityService.countAllCapacitys();
        Assert.assertTrue("Counter for 'Capacity' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CapacityIntegrationTest.testFindCapacity() {
        Capacity obj = dod.getRandomCapacity();
        Assert.assertNotNull("Data on demand for 'Capacity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Capacity' failed to provide an identifier", id);
        obj = capacityService.findCapacity(id);
        Assert.assertNotNull("Find method for 'Capacity' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Capacity' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CapacityIntegrationTest.testFindAllCapacitys() {
        Assert.assertNotNull("Data on demand for 'Capacity' failed to initialize correctly", dod.getRandomCapacity());
        long count = capacityService.countAllCapacitys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Capacity', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Capacity> result = capacityService.findAllCapacitys();
        Assert.assertNotNull("Find all method for 'Capacity' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Capacity' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CapacityIntegrationTest.testFindCapacityEntries() {
        Assert.assertNotNull("Data on demand for 'Capacity' failed to initialize correctly", dod.getRandomCapacity());
        long count = capacityService.countAllCapacitys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Capacity> result = capacityService.findCapacityEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Capacity' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Capacity' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CapacityIntegrationTest.testFlush() {
        Capacity obj = dod.getRandomCapacity();
        Assert.assertNotNull("Data on demand for 'Capacity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Capacity' failed to provide an identifier", id);
        obj = capacityService.findCapacity(id);
        Assert.assertNotNull("Find method for 'Capacity' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCapacity(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Capacity' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CapacityIntegrationTest.testUpdateCapacityUpdate() {
        Capacity obj = dod.getRandomCapacity();
        Assert.assertNotNull("Data on demand for 'Capacity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Capacity' failed to provide an identifier", id);
        obj = capacityService.findCapacity(id);
        boolean modified =  dod.modifyCapacity(obj);
        Integer currentVersion = obj.getVersion();
        Capacity merged = (Capacity)capacityService.updateCapacity(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Capacity' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CapacityIntegrationTest.testSaveCapacity() {
        Assert.assertNotNull("Data on demand for 'Capacity' failed to initialize correctly", dod.getRandomCapacity());
        Capacity obj = dod.getNewTransientCapacity(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Capacity' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Capacity' identifier to be null", obj.getId());
        try {
            capacityService.saveCapacity(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Capacity' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CapacityIntegrationTest.testDeleteCapacity() {
        Capacity obj = dod.getRandomCapacity();
        Assert.assertNotNull("Data on demand for 'Capacity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Capacity' failed to provide an identifier", id);
        obj = capacityService.findCapacity(id);
        capacityService.deleteCapacity(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Capacity' with identifier '" + id + "'", capacityService.findCapacity(id));
    }
    
}
