// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.CapacityEntryDataOnDemand;
import com.hpe.ao.domain.transaction.CapacityEntryIntegrationTest;
import com.hpe.ao.service.CapacityEntryService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CapacityEntryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CapacityEntryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CapacityEntryIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CapacityEntryIntegrationTest: @Transactional;
    
    @Autowired
    CapacityEntryDataOnDemand CapacityEntryIntegrationTest.dod;
    
    @Autowired
    CapacityEntryService CapacityEntryIntegrationTest.capacityEntryService;
    
    @Test
    public void CapacityEntryIntegrationTest.testCountAllCapacityEntrys() {
        Assert.assertNotNull("Data on demand for 'CapacityEntry' failed to initialize correctly", dod.getRandomCapacityEntry());
        long count = capacityEntryService.countAllCapacityEntrys();
        Assert.assertTrue("Counter for 'CapacityEntry' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CapacityEntryIntegrationTest.testFindCapacityEntry() {
        CapacityEntry obj = dod.getRandomCapacityEntry();
        Assert.assertNotNull("Data on demand for 'CapacityEntry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CapacityEntry' failed to provide an identifier", id);
        obj = capacityEntryService.findCapacityEntry(id);
        Assert.assertNotNull("Find method for 'CapacityEntry' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CapacityEntry' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CapacityEntryIntegrationTest.testFindAllCapacityEntrys() {
        Assert.assertNotNull("Data on demand for 'CapacityEntry' failed to initialize correctly", dod.getRandomCapacityEntry());
        long count = capacityEntryService.countAllCapacityEntrys();
        Assert.assertTrue("Too expensive to perform a find all test for 'CapacityEntry', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CapacityEntry> result = capacityEntryService.findAllCapacityEntrys();
        Assert.assertNotNull("Find all method for 'CapacityEntry' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CapacityEntry' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CapacityEntryIntegrationTest.testFindCapacityEntryEntries() {
        Assert.assertNotNull("Data on demand for 'CapacityEntry' failed to initialize correctly", dod.getRandomCapacityEntry());
        long count = capacityEntryService.countAllCapacityEntrys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CapacityEntry> result = capacityEntryService.findCapacityEntryEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CapacityEntry' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CapacityEntry' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CapacityEntryIntegrationTest.testFlush() {
        CapacityEntry obj = dod.getRandomCapacityEntry();
        Assert.assertNotNull("Data on demand for 'CapacityEntry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CapacityEntry' failed to provide an identifier", id);
        obj = capacityEntryService.findCapacityEntry(id);
        Assert.assertNotNull("Find method for 'CapacityEntry' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCapacityEntry(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'CapacityEntry' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CapacityEntryIntegrationTest.testUpdateCapacityEntryUpdate() {
        CapacityEntry obj = dod.getRandomCapacityEntry();
        Assert.assertNotNull("Data on demand for 'CapacityEntry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CapacityEntry' failed to provide an identifier", id);
        obj = capacityEntryService.findCapacityEntry(id);
        boolean modified =  dod.modifyCapacityEntry(obj);
        Integer currentVersion = obj.getVersion();
        CapacityEntry merged = (CapacityEntry)capacityEntryService.updateCapacityEntry(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CapacityEntry' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CapacityEntryIntegrationTest.testSaveCapacityEntry() {
        Assert.assertNotNull("Data on demand for 'CapacityEntry' failed to initialize correctly", dod.getRandomCapacityEntry());
        CapacityEntry obj = dod.getNewTransientCapacityEntry(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CapacityEntry' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CapacityEntry' identifier to be null", obj.getId());
        try {
            capacityEntryService.saveCapacityEntry(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'CapacityEntry' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CapacityEntryIntegrationTest.testDeleteCapacityEntry() {
        CapacityEntry obj = dod.getRandomCapacityEntry();
        Assert.assertNotNull("Data on demand for 'CapacityEntry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CapacityEntry' failed to provide an identifier", id);
        obj = capacityEntryService.findCapacityEntry(id);
        capacityEntryService.deleteCapacityEntry(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'CapacityEntry' with identifier '" + id + "'", capacityEntryService.findCapacityEntry(id));
    }
    
}
