// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.FeatureDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FeatureDataOnDemand_Roo_Configurable {
    
    declare @type: FeatureDataOnDemand: @Configurable;
    
}
