// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.FeatureDataOnDemand;
import com.hpe.ao.domain.transaction.FeatureIntegrationTest;
import com.hpe.ao.service.FeatureService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FeatureIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FeatureIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FeatureIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FeatureIntegrationTest: @Transactional;
    
    @Autowired
    FeatureDataOnDemand FeatureIntegrationTest.dod;
    
    @Autowired
    FeatureService FeatureIntegrationTest.featureService;
    
    @Test
    public void FeatureIntegrationTest.testCountAllFeatures() {
        Assert.assertNotNull("Data on demand for 'Feature' failed to initialize correctly", dod.getRandomFeature());
        long count = featureService.countAllFeatures();
        Assert.assertTrue("Counter for 'Feature' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FeatureIntegrationTest.testFindFeature() {
        Feature obj = dod.getRandomFeature();
        Assert.assertNotNull("Data on demand for 'Feature' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Feature' failed to provide an identifier", id);
        obj = featureService.findFeature(id);
        Assert.assertNotNull("Find method for 'Feature' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Feature' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FeatureIntegrationTest.testFindAllFeatures() {
        Assert.assertNotNull("Data on demand for 'Feature' failed to initialize correctly", dod.getRandomFeature());
        long count = featureService.countAllFeatures();
        Assert.assertTrue("Too expensive to perform a find all test for 'Feature', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Feature> result = featureService.findAllFeatures();
        Assert.assertNotNull("Find all method for 'Feature' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Feature' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FeatureIntegrationTest.testFindFeatureEntries() {
        Assert.assertNotNull("Data on demand for 'Feature' failed to initialize correctly", dod.getRandomFeature());
        long count = featureService.countAllFeatures();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Feature> result = featureService.findFeatureEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Feature' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Feature' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FeatureIntegrationTest.testFlush() {
        Feature obj = dod.getRandomFeature();
        Assert.assertNotNull("Data on demand for 'Feature' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Feature' failed to provide an identifier", id);
        obj = featureService.findFeature(id);
        Assert.assertNotNull("Find method for 'Feature' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFeature(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Feature' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FeatureIntegrationTest.testUpdateFeatureUpdate() {
        Feature obj = dod.getRandomFeature();
        Assert.assertNotNull("Data on demand for 'Feature' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Feature' failed to provide an identifier", id);
        obj = featureService.findFeature(id);
        boolean modified =  dod.modifyFeature(obj);
        Integer currentVersion = obj.getVersion();
        Feature merged = (Feature)featureService.updateFeature(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Feature' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FeatureIntegrationTest.testSaveFeature() {
        Assert.assertNotNull("Data on demand for 'Feature' failed to initialize correctly", dod.getRandomFeature());
        Feature obj = dod.getNewTransientFeature(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Feature' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Feature' identifier to be null", obj.getId());
        try {
            featureService.saveFeature(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Feature' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FeatureIntegrationTest.testDeleteFeature() {
        Feature obj = dod.getRandomFeature();
        Assert.assertNotNull("Data on demand for 'Feature' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Feature' failed to provide an identifier", id);
        obj = featureService.findFeature(id);
        featureService.deleteFeature(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Feature' with identifier '" + id + "'", featureService.findFeature(id));
    }
    
}
