// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.PrgPrjSelectMenuDataOnDemand;
import com.hpe.ao.domain.transaction.PrgPrjSelectMenuIntegrationTest;
import com.hpe.ao.service.PrgPrjSelectMenuService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PrgPrjSelectMenuIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PrgPrjSelectMenuIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PrgPrjSelectMenuIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PrgPrjSelectMenuIntegrationTest: @Transactional;
    
    @Autowired
    PrgPrjSelectMenuDataOnDemand PrgPrjSelectMenuIntegrationTest.dod;
    
    @Autowired
    PrgPrjSelectMenuService PrgPrjSelectMenuIntegrationTest.prgPrjSelectMenuService;
    
    @Test
    public void PrgPrjSelectMenuIntegrationTest.testCountAllPrgPrjSelectMenus() {
        Assert.assertNotNull("Data on demand for 'PrgPrjSelectMenu' failed to initialize correctly", dod.getRandomPrgPrjSelectMenu());
        long count = prgPrjSelectMenuService.countAllPrgPrjSelectMenus();
        Assert.assertTrue("Counter for 'PrgPrjSelectMenu' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PrgPrjSelectMenuIntegrationTest.testFindPrgPrjSelectMenu() {
        PrgPrjSelectMenu obj = dod.getRandomPrgPrjSelectMenu();
        Assert.assertNotNull("Data on demand for 'PrgPrjSelectMenu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PrgPrjSelectMenu' failed to provide an identifier", id);
        obj = prgPrjSelectMenuService.findPrgPrjSelectMenu(id);
        Assert.assertNotNull("Find method for 'PrgPrjSelectMenu' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PrgPrjSelectMenu' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PrgPrjSelectMenuIntegrationTest.testFindAllPrgPrjSelectMenus() {
        Assert.assertNotNull("Data on demand for 'PrgPrjSelectMenu' failed to initialize correctly", dod.getRandomPrgPrjSelectMenu());
        long count = prgPrjSelectMenuService.countAllPrgPrjSelectMenus();
        Assert.assertTrue("Too expensive to perform a find all test for 'PrgPrjSelectMenu', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PrgPrjSelectMenu> result = prgPrjSelectMenuService.findAllPrgPrjSelectMenus();
        Assert.assertNotNull("Find all method for 'PrgPrjSelectMenu' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PrgPrjSelectMenu' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PrgPrjSelectMenuIntegrationTest.testFindPrgPrjSelectMenuEntries() {
        Assert.assertNotNull("Data on demand for 'PrgPrjSelectMenu' failed to initialize correctly", dod.getRandomPrgPrjSelectMenu());
        long count = prgPrjSelectMenuService.countAllPrgPrjSelectMenus();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PrgPrjSelectMenu> result = prgPrjSelectMenuService.findPrgPrjSelectMenuEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PrgPrjSelectMenu' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PrgPrjSelectMenu' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PrgPrjSelectMenuIntegrationTest.testFlush() {
        PrgPrjSelectMenu obj = dod.getRandomPrgPrjSelectMenu();
        Assert.assertNotNull("Data on demand for 'PrgPrjSelectMenu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PrgPrjSelectMenu' failed to provide an identifier", id);
        obj = prgPrjSelectMenuService.findPrgPrjSelectMenu(id);
        Assert.assertNotNull("Find method for 'PrgPrjSelectMenu' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPrgPrjSelectMenu(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PrgPrjSelectMenu' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PrgPrjSelectMenuIntegrationTest.testUpdatePrgPrjSelectMenuUpdate() {
        PrgPrjSelectMenu obj = dod.getRandomPrgPrjSelectMenu();
        Assert.assertNotNull("Data on demand for 'PrgPrjSelectMenu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PrgPrjSelectMenu' failed to provide an identifier", id);
        obj = prgPrjSelectMenuService.findPrgPrjSelectMenu(id);
        boolean modified =  dod.modifyPrgPrjSelectMenu(obj);
        Integer currentVersion = obj.getVersion();
        PrgPrjSelectMenu merged = (PrgPrjSelectMenu)prgPrjSelectMenuService.updatePrgPrjSelectMenu(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PrgPrjSelectMenu' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PrgPrjSelectMenuIntegrationTest.testSavePrgPrjSelectMenu() {
        Assert.assertNotNull("Data on demand for 'PrgPrjSelectMenu' failed to initialize correctly", dod.getRandomPrgPrjSelectMenu());
        PrgPrjSelectMenu obj = dod.getNewTransientPrgPrjSelectMenu(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PrgPrjSelectMenu' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PrgPrjSelectMenu' identifier to be null", obj.getId());
        try {
            prgPrjSelectMenuService.savePrgPrjSelectMenu(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PrgPrjSelectMenu' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PrgPrjSelectMenuIntegrationTest.testDeletePrgPrjSelectMenu() {
        PrgPrjSelectMenu obj = dod.getRandomPrgPrjSelectMenu();
        Assert.assertNotNull("Data on demand for 'PrgPrjSelectMenu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PrgPrjSelectMenu' failed to provide an identifier", id);
        obj = prgPrjSelectMenuService.findPrgPrjSelectMenu(id);
        prgPrjSelectMenuService.deletePrgPrjSelectMenu(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'PrgPrjSelectMenu' with identifier '" + id + "'", prgPrjSelectMenuService.findPrgPrjSelectMenu(id));
    }
    
}
