// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.PrgPrjInitSetupDataOnDemand;
import com.hpe.ao.domain.transaction.PrgPrjInitSetupIntegrationTest;
import com.hpe.ao.service.PrgPrjInitSetupService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PrgPrjInitSetupIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PrgPrjInitSetupIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PrgPrjInitSetupIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PrgPrjInitSetupIntegrationTest: @Transactional;
    
    @Autowired
    PrgPrjInitSetupDataOnDemand PrgPrjInitSetupIntegrationTest.dod;
    
    @Autowired
    PrgPrjInitSetupService PrgPrjInitSetupIntegrationTest.prgPrjInitSetupService;
    
    @Test
    public void PrgPrjInitSetupIntegrationTest.testCountAllPrgPrjInitSetups() {
        Assert.assertNotNull("Data on demand for 'PrgPrjInitSetup' failed to initialize correctly", dod.getRandomPrgPrjInitSetup());
        long count = prgPrjInitSetupService.countAllPrgPrjInitSetups();
        Assert.assertTrue("Counter for 'PrgPrjInitSetup' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PrgPrjInitSetupIntegrationTest.testFindPrgPrjInitSetup() {
        PrgPrjInitSetup obj = dod.getRandomPrgPrjInitSetup();
        Assert.assertNotNull("Data on demand for 'PrgPrjInitSetup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PrgPrjInitSetup' failed to provide an identifier", id);
        obj = prgPrjInitSetupService.findPrgPrjInitSetup(id);
        Assert.assertNotNull("Find method for 'PrgPrjInitSetup' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PrgPrjInitSetup' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PrgPrjInitSetupIntegrationTest.testFindAllPrgPrjInitSetups() {
        Assert.assertNotNull("Data on demand for 'PrgPrjInitSetup' failed to initialize correctly", dod.getRandomPrgPrjInitSetup());
        long count = prgPrjInitSetupService.countAllPrgPrjInitSetups();
        Assert.assertTrue("Too expensive to perform a find all test for 'PrgPrjInitSetup', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PrgPrjInitSetup> result = prgPrjInitSetupService.findAllPrgPrjInitSetups();
        Assert.assertNotNull("Find all method for 'PrgPrjInitSetup' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PrgPrjInitSetup' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PrgPrjInitSetupIntegrationTest.testFindPrgPrjInitSetupEntries() {
        Assert.assertNotNull("Data on demand for 'PrgPrjInitSetup' failed to initialize correctly", dod.getRandomPrgPrjInitSetup());
        long count = prgPrjInitSetupService.countAllPrgPrjInitSetups();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PrgPrjInitSetup> result = prgPrjInitSetupService.findPrgPrjInitSetupEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PrgPrjInitSetup' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PrgPrjInitSetup' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PrgPrjInitSetupIntegrationTest.testFlush() {
        PrgPrjInitSetup obj = dod.getRandomPrgPrjInitSetup();
        Assert.assertNotNull("Data on demand for 'PrgPrjInitSetup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PrgPrjInitSetup' failed to provide an identifier", id);
        obj = prgPrjInitSetupService.findPrgPrjInitSetup(id);
        Assert.assertNotNull("Find method for 'PrgPrjInitSetup' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPrgPrjInitSetup(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PrgPrjInitSetup' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PrgPrjInitSetupIntegrationTest.testUpdatePrgPrjInitSetupUpdate() {
        PrgPrjInitSetup obj = dod.getRandomPrgPrjInitSetup();
        Assert.assertNotNull("Data on demand for 'PrgPrjInitSetup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PrgPrjInitSetup' failed to provide an identifier", id);
        obj = prgPrjInitSetupService.findPrgPrjInitSetup(id);
        boolean modified =  dod.modifyPrgPrjInitSetup(obj);
        Integer currentVersion = obj.getVersion();
        PrgPrjInitSetup merged = (PrgPrjInitSetup)prgPrjInitSetupService.updatePrgPrjInitSetup(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PrgPrjInitSetup' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PrgPrjInitSetupIntegrationTest.testSavePrgPrjInitSetup() {
        Assert.assertNotNull("Data on demand for 'PrgPrjInitSetup' failed to initialize correctly", dod.getRandomPrgPrjInitSetup());
        PrgPrjInitSetup obj = dod.getNewTransientPrgPrjInitSetup(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PrgPrjInitSetup' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PrgPrjInitSetup' identifier to be null", obj.getId());
        try {
            prgPrjInitSetupService.savePrgPrjInitSetup(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PrgPrjInitSetup' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PrgPrjInitSetupIntegrationTest.testDeletePrgPrjInitSetup() {
        PrgPrjInitSetup obj = dod.getRandomPrgPrjInitSetup();
        Assert.assertNotNull("Data on demand for 'PrgPrjInitSetup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PrgPrjInitSetup' failed to provide an identifier", id);
        obj = prgPrjInitSetupService.findPrgPrjInitSetup(id);
        prgPrjInitSetupService.deletePrgPrjInitSetup(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'PrgPrjInitSetup' with identifier '" + id + "'", prgPrjInitSetupService.findPrgPrjInitSetup(id));
    }
    
}
