// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.PrgPrjInitSetup;
import com.hpe.ao.domain.transaction.PrgPrjInitSetupDataOnDemand;
import com.hpe.ao.service.PrgPrjInitSetupService;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PrgPrjInitSetupDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PrgPrjInitSetupDataOnDemand: @Component;
    
    private Random PrgPrjInitSetupDataOnDemand.rnd = new SecureRandom();
    
    private List<PrgPrjInitSetup> PrgPrjInitSetupDataOnDemand.data;
    
    @Autowired
    PrgPrjInitSetupService PrgPrjInitSetupDataOnDemand.prgPrjInitSetupService;
    
    public PrgPrjInitSetup PrgPrjInitSetupDataOnDemand.getNewTransientPrgPrjInitSetup(int index) {
        PrgPrjInitSetup obj = new PrgPrjInitSetup();
        setApplication111(obj, index);
        setApplication112(obj, index);
        setApplication113(obj, index);
        setApplication114(obj, index);
        setApplication121(obj, index);
        setApplication122(obj, index);
        setApplication123(obj, index);
        setApplication124(obj, index);
        setApplication131(obj, index);
        setApplication132(obj, index);
        setApplication133(obj, index);
        setApplication134(obj, index);
        setOrgName(obj, index);
        setProgram1(obj, index);
        setProject11(obj, index);
        setProject11TeamAveragePointDaily(obj, index);
        setProject11TeamCount(obj, index);
        setProject11TeamSize(obj, index);
        setProject12(obj, index);
        setProject12TeamAveragePointDaily(obj, index);
        setProject12TeamCount(obj, index);
        setProject12TeamSize(obj, index);
        setProject13(obj, index);
        setProject13TeamAveragePointDaily(obj, index);
        setProject13TeamCount(obj, index);
        setProject13TeamSize(obj, index);
        setRelease111(obj, index);
        setRelease121(obj, index);
        setRelease131(obj, index);
        setStartDateBaseline(obj, index);
        return obj;
    }
    
    public void PrgPrjInitSetupDataOnDemand.setApplication111(PrgPrjInitSetup obj, int index) {
        String application111 = "application111_" + index;
        if (application111.length() > 30) {
            application111 = application111.substring(0, 30);
        }
        obj.setApplication111(application111);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setApplication112(PrgPrjInitSetup obj, int index) {
        String application112 = "application112_" + index;
        if (application112.length() > 30) {
            application112 = application112.substring(0, 30);
        }
        obj.setApplication112(application112);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setApplication113(PrgPrjInitSetup obj, int index) {
        String application113 = "application113_" + index;
        if (application113.length() > 30) {
            application113 = application113.substring(0, 30);
        }
        obj.setApplication113(application113);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setApplication114(PrgPrjInitSetup obj, int index) {
        String application114 = "application114_" + index;
        if (application114.length() > 30) {
            application114 = application114.substring(0, 30);
        }
        obj.setApplication114(application114);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setApplication121(PrgPrjInitSetup obj, int index) {
        String application121 = "application121_" + index;
        if (application121.length() > 30) {
            application121 = application121.substring(0, 30);
        }
        obj.setApplication121(application121);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setApplication122(PrgPrjInitSetup obj, int index) {
        String application122 = "application122_" + index;
        if (application122.length() > 30) {
            application122 = application122.substring(0, 30);
        }
        obj.setApplication122(application122);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setApplication123(PrgPrjInitSetup obj, int index) {
        String application123 = "application123_" + index;
        if (application123.length() > 30) {
            application123 = application123.substring(0, 30);
        }
        obj.setApplication123(application123);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setApplication124(PrgPrjInitSetup obj, int index) {
        String application124 = "application124_" + index;
        if (application124.length() > 30) {
            application124 = application124.substring(0, 30);
        }
        obj.setApplication124(application124);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setApplication131(PrgPrjInitSetup obj, int index) {
        String application131 = "application131_" + index;
        if (application131.length() > 30) {
            application131 = application131.substring(0, 30);
        }
        obj.setApplication131(application131);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setApplication132(PrgPrjInitSetup obj, int index) {
        String application132 = "application132_" + index;
        if (application132.length() > 30) {
            application132 = application132.substring(0, 30);
        }
        obj.setApplication132(application132);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setApplication133(PrgPrjInitSetup obj, int index) {
        String application133 = "application133_" + index;
        if (application133.length() > 30) {
            application133 = application133.substring(0, 30);
        }
        obj.setApplication133(application133);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setApplication134(PrgPrjInitSetup obj, int index) {
        String application134 = "application134_" + index;
        if (application134.length() > 30) {
            application134 = application134.substring(0, 30);
        }
        obj.setApplication134(application134);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setOrgName(PrgPrjInitSetup obj, int index) {
        String orgName = "orgName_" + index;
        if (orgName.length() > 30) {
            orgName = orgName.substring(0, 30);
        }
        obj.setOrgName(orgName);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setProgram1(PrgPrjInitSetup obj, int index) {
        String program1 = "program1_" + index;
        if (program1.length() > 30) {
            program1 = program1.substring(0, 30);
        }
        obj.setProgram1(program1);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setProject11(PrgPrjInitSetup obj, int index) {
        String project11 = "project11_" + index;
        if (project11.length() > 30) {
            project11 = project11.substring(0, 30);
        }
        obj.setProject11(project11);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setProject11TeamAveragePointDaily(PrgPrjInitSetup obj, int index) {
        BigDecimal project11TeamAveragePointDaily = BigDecimal.valueOf(index);
        obj.setProject11TeamAveragePointDaily(project11TeamAveragePointDaily);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setProject11TeamCount(PrgPrjInitSetup obj, int index) {
        BigDecimal project11TeamCount = BigDecimal.valueOf(index);
        obj.setProject11TeamCount(project11TeamCount);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setProject11TeamSize(PrgPrjInitSetup obj, int index) {
        BigDecimal project11TeamSize = BigDecimal.valueOf(index);
        obj.setProject11TeamSize(project11TeamSize);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setProject12(PrgPrjInitSetup obj, int index) {
        String project12 = "project12_" + index;
        if (project12.length() > 30) {
            project12 = project12.substring(0, 30);
        }
        obj.setProject12(project12);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setProject12TeamAveragePointDaily(PrgPrjInitSetup obj, int index) {
        BigDecimal project12TeamAveragePointDaily = BigDecimal.valueOf(index);
        obj.setProject12TeamAveragePointDaily(project12TeamAveragePointDaily);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setProject12TeamCount(PrgPrjInitSetup obj, int index) {
        BigDecimal project12TeamCount = BigDecimal.valueOf(index);
        obj.setProject12TeamCount(project12TeamCount);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setProject12TeamSize(PrgPrjInitSetup obj, int index) {
        BigDecimal project12TeamSize = BigDecimal.valueOf(index);
        obj.setProject12TeamSize(project12TeamSize);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setProject13(PrgPrjInitSetup obj, int index) {
        String project13 = "project13_" + index;
        if (project13.length() > 30) {
            project13 = project13.substring(0, 30);
        }
        obj.setProject13(project13);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setProject13TeamAveragePointDaily(PrgPrjInitSetup obj, int index) {
        BigDecimal project13TeamAveragePointDaily = BigDecimal.valueOf(index);
        obj.setProject13TeamAveragePointDaily(project13TeamAveragePointDaily);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setProject13TeamCount(PrgPrjInitSetup obj, int index) {
        BigDecimal project13TeamCount = BigDecimal.valueOf(index);
        obj.setProject13TeamCount(project13TeamCount);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setProject13TeamSize(PrgPrjInitSetup obj, int index) {
        BigDecimal project13TeamSize = BigDecimal.valueOf(index);
        obj.setProject13TeamSize(project13TeamSize);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setRelease111(PrgPrjInitSetup obj, int index) {
        String release111 = "release111_" + index;
        if (release111.length() > 30) {
            release111 = release111.substring(0, 30);
        }
        obj.setRelease111(release111);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setRelease121(PrgPrjInitSetup obj, int index) {
        String release121 = "release121_" + index;
        if (release121.length() > 30) {
            release121 = release121.substring(0, 30);
        }
        obj.setRelease121(release121);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setRelease131(PrgPrjInitSetup obj, int index) {
        String release131 = "release131_" + index;
        if (release131.length() > 30) {
            release131 = release131.substring(0, 30);
        }
        obj.setRelease131(release131);
    }
    
    public void PrgPrjInitSetupDataOnDemand.setStartDateBaseline(PrgPrjInitSetup obj, int index) {
        Date startDateBaseline = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setStartDateBaseline(startDateBaseline);
    }
    
    public PrgPrjInitSetup PrgPrjInitSetupDataOnDemand.getSpecificPrgPrjInitSetup(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PrgPrjInitSetup obj = data.get(index);
        Long id = obj.getId();
        return prgPrjInitSetupService.findPrgPrjInitSetup(id);
    }
    
    public PrgPrjInitSetup PrgPrjInitSetupDataOnDemand.getRandomPrgPrjInitSetup() {
        init();
        PrgPrjInitSetup obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return prgPrjInitSetupService.findPrgPrjInitSetup(id);
    }
    
    public boolean PrgPrjInitSetupDataOnDemand.modifyPrgPrjInitSetup(PrgPrjInitSetup obj) {
        return false;
    }
    
    public void PrgPrjInitSetupDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = prgPrjInitSetupService.findPrgPrjInitSetupEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PrgPrjInitSetup' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PrgPrjInitSetup>();
        for (int i = 0; i < 10; i++) {
            PrgPrjInitSetup obj = getNewTransientPrgPrjInitSetup(i);
            try {
                prgPrjInitSetupService.savePrgPrjInitSetup(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
