// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.ProgramIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ProgramIntegrationTest_Roo_Configurable {
    
    declare @type: ProgramIntegrationTest: @Configurable;
    
}
