// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.transaction;

import com.hpe.ao.domain.transaction.ProgressEntryDataOnDemand;
import com.hpe.ao.domain.transaction.ProgressEntryIntegrationTest;
import com.hpe.ao.service.ProgressEntryService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProgressEntryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProgressEntryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProgressEntryIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProgressEntryIntegrationTest: @Transactional;
    
    @Autowired
    ProgressEntryDataOnDemand ProgressEntryIntegrationTest.dod;
    
    @Autowired
    ProgressEntryService ProgressEntryIntegrationTest.progressEntryService;
    
    @Test
    public void ProgressEntryIntegrationTest.testCountAllProgressEntrys() {
        Assert.assertNotNull("Data on demand for 'ProgressEntry' failed to initialize correctly", dod.getRandomProgressEntry());
        long count = progressEntryService.countAllProgressEntrys();
        Assert.assertTrue("Counter for 'ProgressEntry' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProgressEntryIntegrationTest.testFindProgressEntry() {
        ProgressEntry obj = dod.getRandomProgressEntry();
        Assert.assertNotNull("Data on demand for 'ProgressEntry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProgressEntry' failed to provide an identifier", id);
        obj = progressEntryService.findProgressEntry(id);
        Assert.assertNotNull("Find method for 'ProgressEntry' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProgressEntry' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProgressEntryIntegrationTest.testFindAllProgressEntrys() {
        Assert.assertNotNull("Data on demand for 'ProgressEntry' failed to initialize correctly", dod.getRandomProgressEntry());
        long count = progressEntryService.countAllProgressEntrys();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProgressEntry', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProgressEntry> result = progressEntryService.findAllProgressEntrys();
        Assert.assertNotNull("Find all method for 'ProgressEntry' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProgressEntry' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProgressEntryIntegrationTest.testFindProgressEntryEntries() {
        Assert.assertNotNull("Data on demand for 'ProgressEntry' failed to initialize correctly", dod.getRandomProgressEntry());
        long count = progressEntryService.countAllProgressEntrys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProgressEntry> result = progressEntryService.findProgressEntryEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProgressEntry' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProgressEntry' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProgressEntryIntegrationTest.testFlush() {
        ProgressEntry obj = dod.getRandomProgressEntry();
        Assert.assertNotNull("Data on demand for 'ProgressEntry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProgressEntry' failed to provide an identifier", id);
        obj = progressEntryService.findProgressEntry(id);
        Assert.assertNotNull("Find method for 'ProgressEntry' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProgressEntry(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ProgressEntry' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProgressEntryIntegrationTest.testUpdateProgressEntryUpdate() {
        ProgressEntry obj = dod.getRandomProgressEntry();
        Assert.assertNotNull("Data on demand for 'ProgressEntry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProgressEntry' failed to provide an identifier", id);
        obj = progressEntryService.findProgressEntry(id);
        boolean modified =  dod.modifyProgressEntry(obj);
        Integer currentVersion = obj.getVersion();
        ProgressEntry merged = (ProgressEntry)progressEntryService.updateProgressEntry(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ProgressEntry' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProgressEntryIntegrationTest.testSaveProgressEntry() {
        Assert.assertNotNull("Data on demand for 'ProgressEntry' failed to initialize correctly", dod.getRandomProgressEntry());
        ProgressEntry obj = dod.getNewTransientProgressEntry(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProgressEntry' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ProgressEntry' identifier to be null", obj.getId());
        try {
            progressEntryService.saveProgressEntry(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ProgressEntry' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProgressEntryIntegrationTest.testDeleteProgressEntry() {
        ProgressEntry obj = dod.getRandomProgressEntry();
        Assert.assertNotNull("Data on demand for 'ProgressEntry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProgressEntry' failed to provide an identifier", id);
        obj = progressEntryService.findProgressEntry(id);
        progressEntryService.deleteProgressEntry(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'ProgressEntry' with identifier '" + id + "'", progressEntryService.findProgressEntry(id));
    }
    
}
