// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.service;

import com.hpe.ao.domain.transaction.Application;
import com.hpe.ao.service.ApplicationServiceImpl;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ApplicationServiceImpl_Roo_Service {
    
    declare @type: ApplicationServiceImpl: @Service;
    
    declare @type: ApplicationServiceImpl: @Transactional;
    
    public long ApplicationServiceImpl.countAllApplications() {
        return Application.countApplications();
    }
    
    public void ApplicationServiceImpl.deleteApplication(Application application) {
        application.remove();
    }
    
    public Application ApplicationServiceImpl.findApplication(Long id) {
        return Application.findApplication(id);
    }
    
    public List<Application> ApplicationServiceImpl.findAllApplications() {
        return Application.findAllApplications();
    }
    
    public List<Application> ApplicationServiceImpl.findApplicationEntries(int firstResult, int maxResults) {
        return Application.findApplicationEntries(firstResult, maxResults);
    }
    
    public void ApplicationServiceImpl.saveApplication(Application application) {
        application.persist();
    }
    
    public Application ApplicationServiceImpl.updateApplication(Application application) {
        return application.merge();
    }
    
}
