// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.service;

import com.hpe.ao.domain.transaction.Capacity;
import com.hpe.ao.service.CapacityServiceImpl;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CapacityServiceImpl_Roo_Service {
    
    declare @type: CapacityServiceImpl: @Service;
    
    declare @type: CapacityServiceImpl: @Transactional;
    
    public long CapacityServiceImpl.countAllCapacitys() {
        return Capacity.countCapacitys();
    }
    
    public void CapacityServiceImpl.deleteCapacity(Capacity capacity) {
        capacity.remove();
    }
    
    public Capacity CapacityServiceImpl.findCapacity(Long id) {
        return Capacity.findCapacity(id);
    }
    
    public List<Capacity> CapacityServiceImpl.findAllCapacitys() {
        return Capacity.findAllCapacitys();
    }
    
    public List<Capacity> CapacityServiceImpl.findCapacityEntries(int firstResult, int maxResults) {
        return Capacity.findCapacityEntries(firstResult, maxResults);
    }
    
    public void CapacityServiceImpl.saveCapacity(Capacity capacity) {
        capacity.persist();
    }
    
    public Capacity CapacityServiceImpl.updateCapacity(Capacity capacity) {
        return capacity.merge();
    }
    
}
