// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.service;

import com.hpe.ao.domain.transaction.CapacityEntry;
import com.hpe.ao.service.CapacityEntryServiceImpl;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CapacityEntryServiceImpl_Roo_Service {
    
    declare @type: CapacityEntryServiceImpl: @Service;
    
    declare @type: CapacityEntryServiceImpl: @Transactional;
    
    public long CapacityEntryServiceImpl.countAllCapacityEntrys() {
        return CapacityEntry.countCapacityEntrys();
    }
    
    public void CapacityEntryServiceImpl.deleteCapacityEntry(CapacityEntry capacityEntry) {
        capacityEntry.remove();
    }
    
    public CapacityEntry CapacityEntryServiceImpl.findCapacityEntry(Long id) {
        return CapacityEntry.findCapacityEntry(id);
    }
    
    public List<CapacityEntry> CapacityEntryServiceImpl.findAllCapacityEntrys() {
        return CapacityEntry.findAllCapacityEntrys();
    }
    
    public List<CapacityEntry> CapacityEntryServiceImpl.findCapacityEntryEntries(int firstResult, int maxResults) {
        return CapacityEntry.findCapacityEntryEntries(firstResult, maxResults);
    }
    
    public CapacityEntry CapacityEntryServiceImpl.updateCapacityEntry(CapacityEntry capacityEntry) {
        return capacityEntry.merge();
    }
    
}
