// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.service;

import com.hpe.ao.domain.transaction.Feature;
import com.hpe.ao.service.FeatureService;
import java.util.List;

privileged aspect FeatureService_Roo_Service {
    
    public abstract long FeatureService.countAllFeatures();    
    public abstract void FeatureService.deleteFeature(Feature feature);    
    public abstract Feature FeatureService.findFeature(Long id);    
    public abstract List<Feature> FeatureService.findAllFeatures();    
    public abstract List<Feature> FeatureService.findFeatureEntries(int firstResult, int maxResults);    
    public abstract void FeatureService.saveFeature(Feature feature);    
    public abstract Feature FeatureService.updateFeature(Feature feature);    
}
