// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.service;

import com.hpe.ao.domain.transaction.Feature;
import com.hpe.ao.service.FeatureServiceImpl;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FeatureServiceImpl_Roo_Service {
    
    declare @type: FeatureServiceImpl: @Service;
    
    declare @type: FeatureServiceImpl: @Transactional;
    
    public long FeatureServiceImpl.countAllFeatures() {
        return Feature.countFeatures();
    }
    
    public void FeatureServiceImpl.deleteFeature(Feature feature) {
        feature.remove();
    }
    
    public Feature FeatureServiceImpl.findFeature(Long id) {
        return Feature.findFeature(id);
    }
    
    public List<Feature> FeatureServiceImpl.findAllFeatures() {
        return Feature.findAllFeatures();
    }
    
    public List<Feature> FeatureServiceImpl.findFeatureEntries(int firstResult, int maxResults) {
        return Feature.findFeatureEntries(firstResult, maxResults);
    }
    
    public void FeatureServiceImpl.saveFeature(Feature feature) {
        feature.persist();
    }
    
    public Feature FeatureServiceImpl.updateFeature(Feature feature) {
        return feature.merge();
    }
    
}
