// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.service;

import com.hpe.ao.domain.transaction.PrgPrjSelectMenu;
import com.hpe.ao.service.PrgPrjSelectMenuServiceImpl;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PrgPrjSelectMenuServiceImpl_Roo_Service {
    
    declare @type: PrgPrjSelectMenuServiceImpl: @Service;
    
    declare @type: PrgPrjSelectMenuServiceImpl: @Transactional;
    
    public long PrgPrjSelectMenuServiceImpl.countAllPrgPrjSelectMenus() {
        return PrgPrjSelectMenu.countPrgPrjSelectMenus();
    }
    
    public void PrgPrjSelectMenuServiceImpl.deletePrgPrjSelectMenu(PrgPrjSelectMenu prgPrjSelectMenu) {
        prgPrjSelectMenu.remove();
    }
    
    public PrgPrjSelectMenu PrgPrjSelectMenuServiceImpl.findPrgPrjSelectMenu(Long id) {
        return PrgPrjSelectMenu.findPrgPrjSelectMenu(id);
    }
    
    public List<PrgPrjSelectMenu> PrgPrjSelectMenuServiceImpl.findAllPrgPrjSelectMenus() {
        return PrgPrjSelectMenu.findAllPrgPrjSelectMenus();
    }
    
    public List<PrgPrjSelectMenu> PrgPrjSelectMenuServiceImpl.findPrgPrjSelectMenuEntries(int firstResult, int maxResults) {
        return PrgPrjSelectMenu.findPrgPrjSelectMenuEntries(firstResult, maxResults);
    }
    
    public void PrgPrjSelectMenuServiceImpl.savePrgPrjSelectMenu(PrgPrjSelectMenu prgPrjSelectMenu) {
        prgPrjSelectMenu.persist();
    }
    
    public PrgPrjSelectMenu PrgPrjSelectMenuServiceImpl.updatePrgPrjSelectMenu(PrgPrjSelectMenu prgPrjSelectMenu) {
        return prgPrjSelectMenu.merge();
    }
    
}
