// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.service;

import com.hpe.ao.domain.transaction.PrgPrjSelectMenu;
import com.hpe.ao.service.PrgPrjSelectMenuService;
import java.util.List;

privileged aspect PrgPrjSelectMenuService_Roo_Service {
    
    public abstract long PrgPrjSelectMenuService.countAllPrgPrjSelectMenus();    
    public abstract void PrgPrjSelectMenuService.deletePrgPrjSelectMenu(PrgPrjSelectMenu prgPrjSelectMenu);    
    public abstract PrgPrjSelectMenu PrgPrjSelectMenuService.findPrgPrjSelectMenu(Long id);    
    public abstract List<PrgPrjSelectMenu> PrgPrjSelectMenuService.findAllPrgPrjSelectMenus();    
    public abstract List<PrgPrjSelectMenu> PrgPrjSelectMenuService.findPrgPrjSelectMenuEntries(int firstResult, int maxResults);    
    public abstract void PrgPrjSelectMenuService.savePrgPrjSelectMenu(PrgPrjSelectMenu prgPrjSelectMenu);    
    public abstract PrgPrjSelectMenu PrgPrjSelectMenuService.updatePrgPrjSelectMenu(PrgPrjSelectMenu prgPrjSelectMenu);    
}
