// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.service;

import com.hpe.ao.domain.transaction.PrgPrjInitSetup;
import com.hpe.ao.service.PrgPrjInitSetupServiceImpl;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PrgPrjInitSetupServiceImpl_Roo_Service {
    
    declare @type: PrgPrjInitSetupServiceImpl: @Service;
    
    declare @type: PrgPrjInitSetupServiceImpl: @Transactional;
    
    public long PrgPrjInitSetupServiceImpl.countAllPrgPrjInitSetups() {
        return PrgPrjInitSetup.countPrgPrjInitSetups();
    }
    
    public void PrgPrjInitSetupServiceImpl.deletePrgPrjInitSetup(PrgPrjInitSetup prgPrjInitSetup) {
        prgPrjInitSetup.remove();
    }
    
    public PrgPrjInitSetup PrgPrjInitSetupServiceImpl.findPrgPrjInitSetup(Long id) {
        return PrgPrjInitSetup.findPrgPrjInitSetup(id);
    }
    
    public List<PrgPrjInitSetup> PrgPrjInitSetupServiceImpl.findAllPrgPrjInitSetups() {
        return PrgPrjInitSetup.findAllPrgPrjInitSetups();
    }
    
    public List<PrgPrjInitSetup> PrgPrjInitSetupServiceImpl.findPrgPrjInitSetupEntries(int firstResult, int maxResults) {
        return PrgPrjInitSetup.findPrgPrjInitSetupEntries(firstResult, maxResults);
    }
    
    public PrgPrjInitSetup PrgPrjInitSetupServiceImpl.updatePrgPrjInitSetup(PrgPrjInitSetup prgPrjInitSetup) {
        return prgPrjInitSetup.merge();
    }
    
}
