// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.service;

import com.hpe.ao.domain.transaction.PrgPrjInitSetup;
import com.hpe.ao.service.PrgPrjInitSetupService;
import java.util.List;

privileged aspect PrgPrjInitSetupService_Roo_Service {
    
    public abstract long PrgPrjInitSetupService.countAllPrgPrjInitSetups();    
    public abstract void PrgPrjInitSetupService.deletePrgPrjInitSetup(PrgPrjInitSetup prgPrjInitSetup);    
    public abstract PrgPrjInitSetup PrgPrjInitSetupService.findPrgPrjInitSetup(Long id);    
    public abstract List<PrgPrjInitSetup> PrgPrjInitSetupService.findAllPrgPrjInitSetups();    
    public abstract List<PrgPrjInitSetup> PrgPrjInitSetupService.findPrgPrjInitSetupEntries(int firstResult, int maxResults);    
    public abstract void PrgPrjInitSetupService.savePrgPrjInitSetup(PrgPrjInitSetup prgPrjInitSetup);    
    public abstract PrgPrjInitSetup PrgPrjInitSetupService.updatePrgPrjInitSetup(PrgPrjInitSetup prgPrjInitSetup);    
}
