// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.service;

import com.hpe.ao.domain.transaction.Program;
import com.hpe.ao.service.ProgramServiceImpl;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProgramServiceImpl_Roo_Service {
    
    declare @type: ProgramServiceImpl: @Service;
    
    declare @type: ProgramServiceImpl: @Transactional;
    
    public long ProgramServiceImpl.countAllPrograms() {
        return Program.countPrograms();
    }
    
    public void ProgramServiceImpl.deleteProgram(Program program) {
        program.remove();
    }
    
    public Program ProgramServiceImpl.findProgram(Long id) {
        return Program.findProgram(id);
    }
    
    public List<Program> ProgramServiceImpl.findAllPrograms() {
        return Program.findAllPrograms();
    }
    
    public List<Program> ProgramServiceImpl.findProgramEntries(int firstResult, int maxResults) {
        return Program.findProgramEntries(firstResult, maxResults);
    }
    
    public void ProgramServiceImpl.saveProgram(Program program) {
        program.persist();
    }
    
    public Program ProgramServiceImpl.updateProgram(Program program) {
        return program.merge();
    }
    
}
