// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.service;

import com.hpe.ao.domain.transaction.Program;
import com.hpe.ao.service.ProgramService;
import java.util.List;

privileged aspect ProgramService_Roo_Service {
    
    public abstract long ProgramService.countAllPrograms();    
    public abstract void ProgramService.deleteProgram(Program program);    
    public abstract Program ProgramService.findProgram(Long id);    
    public abstract List<Program> ProgramService.findAllPrograms();    
    public abstract List<Program> ProgramService.findProgramEntries(int firstResult, int maxResults);    
    public abstract void ProgramService.saveProgram(Program program);    
    public abstract Program ProgramService.updateProgram(Program program);    
}
