// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.service;

import com.hpe.ao.domain.transaction.ProjectRelease;
import com.hpe.ao.service.ProjectReleaseService;
import java.util.List;

privileged aspect ProjectReleaseService_Roo_Service {
    
    public abstract long ProjectReleaseService.countAllProjectReleases();    
    public abstract void ProjectReleaseService.deleteProjectRelease(ProjectRelease projectRelease);    
    public abstract ProjectRelease ProjectReleaseService.findProjectRelease(Long id);    
    public abstract List<ProjectRelease> ProjectReleaseService.findAllProjectReleases();    
    public abstract List<ProjectRelease> ProjectReleaseService.findProjectReleaseEntries(int firstResult, int maxResults);    
    public abstract void ProjectReleaseService.saveProjectRelease(ProjectRelease projectRelease);    
    public abstract ProjectRelease ProjectReleaseService.updateProjectRelease(ProjectRelease projectRelease);    
}
