// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.service;

import com.hpe.ao.domain.framework.Tag;
import com.hpe.ao.service.TagServiceImpl;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TagServiceImpl_Roo_Service {
    
    declare @type: TagServiceImpl: @Service;
    
    declare @type: TagServiceImpl: @Transactional;
    
    public long TagServiceImpl.countAllTags() {
        return Tag.countTags();
    }
    
    public void TagServiceImpl.deleteTag(Tag tag) {
        tag.remove();
    }
    
    public Tag TagServiceImpl.findTag(Long id) {
        return Tag.findTag(id);
    }
    
    public List<Tag> TagServiceImpl.findAllTags() {
        return Tag.findAllTags();
    }
    
    public List<Tag> TagServiceImpl.findTagEntries(int firstResult, int maxResults) {
        return Tag.findTagEntries(firstResult, maxResults);
    }
    
    public void TagServiceImpl.saveTag(Tag tag) {
        tag.persist();
    }
    
    public Tag TagServiceImpl.updateTag(Tag tag) {
        return tag.merge();
    }
    
}
