// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.service;

import com.hpe.ao.domain.framework.TransactionLog;
import com.hpe.ao.service.TransactionLogService;
import java.util.List;

privileged aspect TransactionLogService_Roo_Service {
    
    public abstract long TransactionLogService.countAllTransactionLogs();    
    public abstract void TransactionLogService.deleteTransactionLog(TransactionLog transactionLog);    
    public abstract TransactionLog TransactionLogService.findTransactionLog(Long id);    
    public abstract List<TransactionLog> TransactionLogService.findAllTransactionLogs();    
    public abstract List<TransactionLog> TransactionLogService.findTransactionLogEntries(int firstResult, int maxResults);    
    public abstract void TransactionLogService.saveTransactionLog(TransactionLog transactionLog);    
    public abstract TransactionLog TransactionLogService.updateTransactionLog(TransactionLog transactionLog);    
}
