// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.web;

import com.hpe.ao.domain.framework.Tag;
import com.hpe.ao.domain.framework.TransactionLog;
import com.hpe.ao.domain.transaction.Application;
import com.hpe.ao.domain.transaction.Capacity;
import com.hpe.ao.domain.transaction.CapacityEntry;
import com.hpe.ao.domain.transaction.Feature;
import com.hpe.ao.domain.transaction.PrgPrjInitSetup;
import com.hpe.ao.domain.transaction.PrgPrjSelectMenu;
import com.hpe.ao.domain.transaction.Program;
import com.hpe.ao.domain.transaction.ProgressEntry;
import com.hpe.ao.domain.transaction.Project;
import com.hpe.ao.domain.transaction.ProjectRelease;
import com.hpe.ao.service.ApplicationService;
import com.hpe.ao.service.CapacityEntryService;
import com.hpe.ao.service.CapacityService;
import com.hpe.ao.service.FeatureService;
import com.hpe.ao.service.PrgPrjInitSetupService;
import com.hpe.ao.service.PrgPrjSelectMenuService;
import com.hpe.ao.service.ProgramService;
import com.hpe.ao.service.ProgressEntryService;
import com.hpe.ao.service.ProjectReleaseService;
import com.hpe.ao.service.ProjectService;
import com.hpe.ao.service.TagService;
import com.hpe.ao.service.TransactionLogService;
import com.hpe.ao.web.ApplicationConversionServiceFactoryBean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.core.convert.converter.Converter;
import org.springframework.format.FormatterRegistry;

privileged aspect ApplicationConversionServiceFactoryBean_Roo_ConversionService {
    
    declare @type: ApplicationConversionServiceFactoryBean: @Configurable;
    
    @Autowired
    TagService ApplicationConversionServiceFactoryBean.tagService;
    
    @Autowired
    TransactionLogService ApplicationConversionServiceFactoryBean.transactionLogService;
    
    @Autowired
    ApplicationService ApplicationConversionServiceFactoryBean.applicationService;
    
    @Autowired
    CapacityService ApplicationConversionServiceFactoryBean.capacityService;
    
    @Autowired
    CapacityEntryService ApplicationConversionServiceFactoryBean.capacityEntryService;
    
    @Autowired
    FeatureService ApplicationConversionServiceFactoryBean.featureService;
    
    @Autowired
    PrgPrjInitSetupService ApplicationConversionServiceFactoryBean.prgPrjInitSetupService;
    
    @Autowired
    PrgPrjSelectMenuService ApplicationConversionServiceFactoryBean.prgPrjSelectMenuService;
    
    @Autowired
    ProgramService ApplicationConversionServiceFactoryBean.programService;
    
    @Autowired
    ProgressEntryService ApplicationConversionServiceFactoryBean.progressEntryService;
    
    @Autowired
    ProjectService ApplicationConversionServiceFactoryBean.projectService;
    
    @Autowired
    ProjectReleaseService ApplicationConversionServiceFactoryBean.projectReleaseService;
    
    public Converter<Tag, String> ApplicationConversionServiceFactoryBean.getTagToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.hpe.ao.domain.framework.Tag, java.lang.String>() {
            public String convert(Tag tag) {
                return new StringBuilder().append(tag.getName()).append(' ').append(tag.getDescription()).append(' ').append(tag.getType()).append(' ').append(tag.getCategory()).toString();
            }
        };
    }
    
    public Converter<Long, Tag> ApplicationConversionServiceFactoryBean.getIdToTagConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.hpe.ao.domain.framework.Tag>() {
            public com.hpe.ao.domain.framework.Tag convert(java.lang.Long id) {
                return tagService.findTag(id);
            }
        };
    }
    
    public Converter<String, Tag> ApplicationConversionServiceFactoryBean.getStringToTagConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.hpe.ao.domain.framework.Tag>() {
            public com.hpe.ao.domain.framework.Tag convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Tag.class);
            }
        };
    }
    
    public Converter<TransactionLog, String> ApplicationConversionServiceFactoryBean.getTransactionLogToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.hpe.ao.domain.framework.TransactionLog, java.lang.String>() {
            public String convert(TransactionLog transactionLog) {
                return new StringBuilder().append(transactionLog.getEntityName()).append(' ').append(transactionLog.getEntiyKey1()).append(' ').append(transactionLog.getEntityKey2()).append(' ').append(transactionLog.getLogUser()).toString();
            }
        };
    }
    
    public Converter<Long, TransactionLog> ApplicationConversionServiceFactoryBean.getIdToTransactionLogConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.hpe.ao.domain.framework.TransactionLog>() {
            public com.hpe.ao.domain.framework.TransactionLog convert(java.lang.Long id) {
                return transactionLogService.findTransactionLog(id);
            }
        };
    }
    
    public Converter<String, TransactionLog> ApplicationConversionServiceFactoryBean.getStringToTransactionLogConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.hpe.ao.domain.framework.TransactionLog>() {
            public com.hpe.ao.domain.framework.TransactionLog convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), TransactionLog.class);
            }
        };
    }
    
    public Converter<Long, Application> ApplicationConversionServiceFactoryBean.getIdToApplicationConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.hpe.ao.domain.transaction.Application>() {
            public com.hpe.ao.domain.transaction.Application convert(java.lang.Long id) {
                return applicationService.findApplication(id);
            }
        };
    }
    
    public Converter<String, Application> ApplicationConversionServiceFactoryBean.getStringToApplicationConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.hpe.ao.domain.transaction.Application>() {
            public com.hpe.ao.domain.transaction.Application convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Application.class);
            }
        };
    }
    
    public Converter<Capacity, String> ApplicationConversionServiceFactoryBean.getCapacityToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.hpe.ao.domain.transaction.Capacity, java.lang.String>() {
            public String convert(Capacity capacity) {
                return new StringBuilder().append(capacity.getEffectiveDate()).append(' ').append(capacity.getEntryComments()).append(' ').append(capacity.getTeamCountBaseline()).append(' ').append(capacity.getTeamSizeBaseline()).toString();
            }
        };
    }
    
    public Converter<Long, Capacity> ApplicationConversionServiceFactoryBean.getIdToCapacityConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.hpe.ao.domain.transaction.Capacity>() {
            public com.hpe.ao.domain.transaction.Capacity convert(java.lang.Long id) {
                return capacityService.findCapacity(id);
            }
        };
    }
    
    public Converter<String, Capacity> ApplicationConversionServiceFactoryBean.getStringToCapacityConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.hpe.ao.domain.transaction.Capacity>() {
            public com.hpe.ao.domain.transaction.Capacity convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Capacity.class);
            }
        };
    }
    
    public Converter<CapacityEntry, String> ApplicationConversionServiceFactoryBean.getCapacityEntryToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.hpe.ao.domain.transaction.CapacityEntry, java.lang.String>() {
            public String convert(CapacityEntry capacityEntry) {
                return new StringBuilder().append(capacityEntry.getStartDate()).append(' ').append(capacityEntry.getEndDate()).append(' ').append(capacityEntry.getTeamCount()).append(' ').append(capacityEntry.getTeamSize()).toString();
            }
        };
    }
    
    public Converter<Long, CapacityEntry> ApplicationConversionServiceFactoryBean.getIdToCapacityEntryConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.hpe.ao.domain.transaction.CapacityEntry>() {
            public com.hpe.ao.domain.transaction.CapacityEntry convert(java.lang.Long id) {
                return capacityEntryService.findCapacityEntry(id);
            }
        };
    }
    
    public Converter<String, CapacityEntry> ApplicationConversionServiceFactoryBean.getStringToCapacityEntryConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.hpe.ao.domain.transaction.CapacityEntry>() {
            public com.hpe.ao.domain.transaction.CapacityEntry convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), CapacityEntry.class);
            }
        };
    }
    
    public Converter<Feature, String> ApplicationConversionServiceFactoryBean.getFeatureToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.hpe.ao.domain.transaction.Feature, java.lang.String>() {
            public String convert(Feature feature) {
                return new StringBuilder().append(feature.getName()).append(' ').append(feature.getDescription()).append(' ').append(feature.getStartDateBaseline()).append(' ').append(feature.getEndDateBaseline()).toString();
            }
        };
    }
    
    public Converter<Long, Feature> ApplicationConversionServiceFactoryBean.getIdToFeatureConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.hpe.ao.domain.transaction.Feature>() {
            public com.hpe.ao.domain.transaction.Feature convert(java.lang.Long id) {
                return featureService.findFeature(id);
            }
        };
    }
    
    public Converter<String, Feature> ApplicationConversionServiceFactoryBean.getStringToFeatureConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.hpe.ao.domain.transaction.Feature>() {
            public com.hpe.ao.domain.transaction.Feature convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Feature.class);
            }
        };
    }
    
    public Converter<PrgPrjInitSetup, String> ApplicationConversionServiceFactoryBean.getPrgPrjInitSetupToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.hpe.ao.domain.transaction.PrgPrjInitSetup, java.lang.String>() {
            public String convert(PrgPrjInitSetup prgPrjInitSetup) {
                return new StringBuilder().append(prgPrjInitSetup.getProgram1()).append(' ').append(prgPrjInitSetup.getOrgName()).append(' ').append(prgPrjInitSetup.getStartDateBaseline()).append(' ').append(prgPrjInitSetup.getProject11()).toString();
            }
        };
    }
    
    public Converter<Long, PrgPrjInitSetup> ApplicationConversionServiceFactoryBean.getIdToPrgPrjInitSetupConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.hpe.ao.domain.transaction.PrgPrjInitSetup>() {
            public com.hpe.ao.domain.transaction.PrgPrjInitSetup convert(java.lang.Long id) {
                return prgPrjInitSetupService.findPrgPrjInitSetup(id);
            }
        };
    }
    
    public Converter<String, PrgPrjInitSetup> ApplicationConversionServiceFactoryBean.getStringToPrgPrjInitSetupConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.hpe.ao.domain.transaction.PrgPrjInitSetup>() {
            public com.hpe.ao.domain.transaction.PrgPrjInitSetup convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), PrgPrjInitSetup.class);
            }
        };
    }
    
    public Converter<PrgPrjSelectMenu, String> ApplicationConversionServiceFactoryBean.getPrgPrjSelectMenuToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.hpe.ao.domain.transaction.PrgPrjSelectMenu, java.lang.String>() {
            public String convert(PrgPrjSelectMenu prgPrjSelectMenu) {
                return new StringBuilder().append(prgPrjSelectMenu.getCreateUser()).toString();
            }
        };
    }
    
    public Converter<Long, PrgPrjSelectMenu> ApplicationConversionServiceFactoryBean.getIdToPrgPrjSelectMenuConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.hpe.ao.domain.transaction.PrgPrjSelectMenu>() {
            public com.hpe.ao.domain.transaction.PrgPrjSelectMenu convert(java.lang.Long id) {
                return prgPrjSelectMenuService.findPrgPrjSelectMenu(id);
            }
        };
    }
    
    public Converter<String, PrgPrjSelectMenu> ApplicationConversionServiceFactoryBean.getStringToPrgPrjSelectMenuConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.hpe.ao.domain.transaction.PrgPrjSelectMenu>() {
            public com.hpe.ao.domain.transaction.PrgPrjSelectMenu convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), PrgPrjSelectMenu.class);
            }
        };
    }
    
    public Converter<Long, Program> ApplicationConversionServiceFactoryBean.getIdToProgramConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.hpe.ao.domain.transaction.Program>() {
            public com.hpe.ao.domain.transaction.Program convert(java.lang.Long id) {
                return programService.findProgram(id);
            }
        };
    }
    
    public Converter<String, Program> ApplicationConversionServiceFactoryBean.getStringToProgramConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.hpe.ao.domain.transaction.Program>() {
            public com.hpe.ao.domain.transaction.Program convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Program.class);
            }
        };
    }
    
    public Converter<ProgressEntry, String> ApplicationConversionServiceFactoryBean.getProgressEntryToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.hpe.ao.domain.transaction.ProgressEntry, java.lang.String>() {
            public String convert(ProgressEntry progressEntry) {
                return new StringBuilder().append(progressEntry.getEffectiveDate()).append(' ').append(progressEntry.getEntryComments()).append(' ').append(progressEntry.getStoryCountComplete()).append(' ').append(progressEntry.getStoryPointComplete()).toString();
            }
        };
    }
    
    public Converter<Long, ProgressEntry> ApplicationConversionServiceFactoryBean.getIdToProgressEntryConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.hpe.ao.domain.transaction.ProgressEntry>() {
            public com.hpe.ao.domain.transaction.ProgressEntry convert(java.lang.Long id) {
                return progressEntryService.findProgressEntry(id);
            }
        };
    }
    
    public Converter<String, ProgressEntry> ApplicationConversionServiceFactoryBean.getStringToProgressEntryConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.hpe.ao.domain.transaction.ProgressEntry>() {
            public com.hpe.ao.domain.transaction.ProgressEntry convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), ProgressEntry.class);
            }
        };
    }
    
    public Converter<Long, Project> ApplicationConversionServiceFactoryBean.getIdToProjectConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.hpe.ao.domain.transaction.Project>() {
            public com.hpe.ao.domain.transaction.Project convert(java.lang.Long id) {
                return projectService.findProject(id);
            }
        };
    }
    
    public Converter<String, Project> ApplicationConversionServiceFactoryBean.getStringToProjectConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.hpe.ao.domain.transaction.Project>() {
            public com.hpe.ao.domain.transaction.Project convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Project.class);
            }
        };
    }
    
    public Converter<Long, ProjectRelease> ApplicationConversionServiceFactoryBean.getIdToProjectReleaseConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.hpe.ao.domain.transaction.ProjectRelease>() {
            public com.hpe.ao.domain.transaction.ProjectRelease convert(java.lang.Long id) {
                return projectReleaseService.findProjectRelease(id);
            }
        };
    }
    
    public Converter<String, ProjectRelease> ApplicationConversionServiceFactoryBean.getStringToProjectReleaseConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.hpe.ao.domain.transaction.ProjectRelease>() {
            public com.hpe.ao.domain.transaction.ProjectRelease convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), ProjectRelease.class);
            }
        };
    }
    
    public void ApplicationConversionServiceFactoryBean.installLabelConverters(FormatterRegistry registry) {
        registry.addConverter(getTagToStringConverter());
        registry.addConverter(getIdToTagConverter());
        registry.addConverter(getStringToTagConverter());
        registry.addConverter(getTransactionLogToStringConverter());
        registry.addConverter(getIdToTransactionLogConverter());
        registry.addConverter(getStringToTransactionLogConverter());
        registry.addConverter(getApplicationToStringConverter());
        registry.addConverter(getIdToApplicationConverter());
        registry.addConverter(getStringToApplicationConverter());
        registry.addConverter(getCapacityToStringConverter());
        registry.addConverter(getIdToCapacityConverter());
        registry.addConverter(getStringToCapacityConverter());
        registry.addConverter(getCapacityEntryToStringConverter());
        registry.addConverter(getIdToCapacityEntryConverter());
        registry.addConverter(getStringToCapacityEntryConverter());
        registry.addConverter(getFeatureToStringConverter());
        registry.addConverter(getIdToFeatureConverter());
        registry.addConverter(getStringToFeatureConverter());
        registry.addConverter(getPrgPrjInitSetupToStringConverter());
        registry.addConverter(getIdToPrgPrjInitSetupConverter());
        registry.addConverter(getStringToPrgPrjInitSetupConverter());
        registry.addConverter(getPrgPrjSelectMenuToStringConverter());
        registry.addConverter(getIdToPrgPrjSelectMenuConverter());
        registry.addConverter(getStringToPrgPrjSelectMenuConverter());
        registry.addConverter(getProgramToStringConverter());
        registry.addConverter(getIdToProgramConverter());
        registry.addConverter(getStringToProgramConverter());
        registry.addConverter(getProgressEntryToStringConverter());
        registry.addConverter(getIdToProgressEntryConverter());
        registry.addConverter(getStringToProgressEntryConverter());
        registry.addConverter(getProjectToStringConverter());
        registry.addConverter(getIdToProjectConverter());
        registry.addConverter(getStringToProjectConverter());
        registry.addConverter(getProjectReleaseToStringConverter());
        registry.addConverter(getIdToProjectReleaseConverter());
        registry.addConverter(getStringToProjectReleaseConverter());
    }
    
    public void ApplicationConversionServiceFactoryBean.afterPropertiesSet() {
        super.afterPropertiesSet();
        installLabelConverters(getObject());
    }
    
}
