// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.web;

import com.hpe.ao.domain.transaction.Capacity;
import com.hpe.ao.domain.transaction.Project;
import com.hpe.ao.service.CapacityService;
import com.hpe.ao.service.ProjectService;
import com.hpe.ao.web.CapacityController;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.joda.time.format.DateTimeFormat;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect CapacityController_Roo_Controller {
    
    @Autowired
    ProjectService CapacityController.projectService;
    
    @Autowired
    CapacityService CapacityController.capacityService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String CapacityController.create(@Valid Capacity capacity, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, capacity);
            return "capacitys/create";
        }
        uiModel.asMap().clear();
        capacityService.saveCapacity(capacity);
        return "redirect:/capacitys/" + encodeUrlPathSegment(capacity.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String CapacityController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Capacity());
        List<String[]> dependencies = new ArrayList<String[]>();
        if (projectService.countAllProjects() == 0) {
            dependencies.add(new String[] { "project", "projects" });
        }
        uiModel.addAttribute("dependencies", dependencies);
        return "capacitys/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String CapacityController.show(@PathVariable("id") Long id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("capacity", capacityService.findCapacity(id));
        uiModel.addAttribute("itemId", id);
        return "capacitys/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String CapacityController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("capacitys", Capacity.findCapacityEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) capacityService.countAllCapacitys() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("capacitys", Capacity.findAllCapacitys(sortFieldName, sortOrder));
        }
        addDateTimeFormatPatterns(uiModel);
        return "capacitys/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String CapacityController.update(@Valid Capacity capacity, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, capacity);
            return "capacitys/update";
        }
        uiModel.asMap().clear();
        capacityService.updateCapacity(capacity);
        return "redirect:/capacitys/" + encodeUrlPathSegment(capacity.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String CapacityController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, capacityService.findCapacity(id));
        return "capacitys/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String CapacityController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Capacity capacity = capacityService.findCapacity(id);
        capacityService.deleteCapacity(capacity);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/capacitys";
    }
    
    void CapacityController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("capacity_effectivedate_date_format", DateTimeFormat.patternForStyle("M-", LocaleContextHolder.getLocale()));
    }
    
    void CapacityController.populateEditForm(Model uiModel, Capacity capacity) {
        uiModel.addAttribute("capacity", capacity);
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("projects", projectService.findAllProjects());
    }
    
    String CapacityController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
