// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.web;

import com.hpe.ao.domain.transaction.CapacityEntry;
import com.hpe.ao.reference.CapacityEntryType;
import com.hpe.ao.service.CapacityEntryService;
import com.hpe.ao.web.CapacityEntryController;
import java.io.UnsupportedEncodingException;
import java.util.Arrays;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.joda.time.format.DateTimeFormat;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect CapacityEntryController_Roo_Controller {
    
    @Autowired
    CapacityEntryService CapacityEntryController.capacityEntryService;
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String CapacityEntryController.show(@PathVariable("id") Long id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("capacityentry", capacityEntryService.findCapacityEntry(id));
        uiModel.addAttribute("itemId", id);
        return "capacityentrys/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String CapacityEntryController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("capacityentrys", CapacityEntry.findCapacityEntryEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) capacityEntryService.countAllCapacityEntrys() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("capacityentrys", CapacityEntry.findAllCapacityEntrys(sortFieldName, sortOrder));
        }
        addDateTimeFormatPatterns(uiModel);
        return "capacityentrys/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String CapacityEntryController.update(@Valid CapacityEntry capacityEntry, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, capacityEntry);
            return "capacityentrys/update";
        }
        uiModel.asMap().clear();
        capacityEntryService.updateCapacityEntry(capacityEntry);
        return "redirect:/capacityentrys/" + encodeUrlPathSegment(capacityEntry.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String CapacityEntryController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, capacityEntryService.findCapacityEntry(id));
        return "capacityentrys/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String CapacityEntryController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        CapacityEntry capacityEntry = capacityEntryService.findCapacityEntry(id);
        capacityEntryService.deleteCapacityEntry(capacityEntry);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/capacityentrys";
    }
    
    void CapacityEntryController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("capacityEntry_startdate_date_format", DateTimeFormat.patternForStyle("M-", LocaleContextHolder.getLocale()));
        uiModel.addAttribute("capacityEntry_enddate_date_format", DateTimeFormat.patternForStyle("M-", LocaleContextHolder.getLocale()));
    }
    
    void CapacityEntryController.populateEditForm(Model uiModel, CapacityEntry capacityEntry) {
        uiModel.addAttribute("capacityEntry", capacityEntry);
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("projects", projectService.findAllProjects());
        uiModel.addAttribute("capacityentrytypes", Arrays.asList(CapacityEntryType.values()));
    }
    
    String CapacityEntryController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
