// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.web;

import com.hpe.ao.domain.transaction.PrgPrjInitSetup;
import com.hpe.ao.web.PrgPrjInitSetupController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.joda.time.format.DateTimeFormat;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect PrgPrjInitSetupController_Roo_Controller {
    
    @RequestMapping(params = "form", produces = "text/html")
    public String PrgPrjInitSetupController.createForm(Model uiModel) {
        populateEditForm(uiModel, new PrgPrjInitSetup());
        return "prgprjinitsetups/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String PrgPrjInitSetupController.show(@PathVariable("id") Long id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("prgprjinitsetup", prgPrjInitSetupService.findPrgPrjInitSetup(id));
        uiModel.addAttribute("itemId", id);
        return "prgprjinitsetups/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String PrgPrjInitSetupController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("prgprjinitsetups", PrgPrjInitSetup.findPrgPrjInitSetupEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) prgPrjInitSetupService.countAllPrgPrjInitSetups() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("prgprjinitsetups", PrgPrjInitSetup.findAllPrgPrjInitSetups(sortFieldName, sortOrder));
        }
        addDateTimeFormatPatterns(uiModel);
        return "prgprjinitsetups/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String PrgPrjInitSetupController.update(@Valid PrgPrjInitSetup prgPrjInitSetup, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, prgPrjInitSetup);
            return "prgprjinitsetups/update";
        }
        uiModel.asMap().clear();
        prgPrjInitSetupService.updatePrgPrjInitSetup(prgPrjInitSetup);
        return "redirect:/prgprjinitsetups/" + encodeUrlPathSegment(prgPrjInitSetup.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String PrgPrjInitSetupController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, prgPrjInitSetupService.findPrgPrjInitSetup(id));
        return "prgprjinitsetups/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String PrgPrjInitSetupController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        PrgPrjInitSetup prgPrjInitSetup = prgPrjInitSetupService.findPrgPrjInitSetup(id);
        prgPrjInitSetupService.deletePrgPrjInitSetup(prgPrjInitSetup);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/prgprjinitsetups";
    }
    
    void PrgPrjInitSetupController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("prgPrjInitSetup_startdatebaseline_date_format", DateTimeFormat.patternForStyle("M-", LocaleContextHolder.getLocale()));
    }
    
    String PrgPrjInitSetupController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
