// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.web;

import com.hpe.ao.domain.transaction.PrgPrjSelectMenu;
import com.hpe.ao.service.PrgPrjSelectMenuService;
import com.hpe.ao.service.ProgramService;
import com.hpe.ao.service.ProjectService;
import com.hpe.ao.web.PrgPrjSelectMenuController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect PrgPrjSelectMenuController_Roo_Controller {
    
    @Autowired
    PrgPrjSelectMenuService PrgPrjSelectMenuController.prgPrjSelectMenuService;
    
    @Autowired
    ProgramService PrgPrjSelectMenuController.programService;
    
    @Autowired
    ProjectService PrgPrjSelectMenuController.projectService;
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String PrgPrjSelectMenuController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("prgprjselectmenu", prgPrjSelectMenuService.findPrgPrjSelectMenu(id));
        uiModel.addAttribute("itemId", id);
        return "prgprjselectmenus/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String PrgPrjSelectMenuController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("prgprjselectmenus", PrgPrjSelectMenu.findPrgPrjSelectMenuEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) prgPrjSelectMenuService.countAllPrgPrjSelectMenus() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("prgprjselectmenus", PrgPrjSelectMenu.findAllPrgPrjSelectMenus(sortFieldName, sortOrder));
        }
        return "prgprjselectmenus/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String PrgPrjSelectMenuController.update(@Valid PrgPrjSelectMenu prgPrjSelectMenu, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, prgPrjSelectMenu);
            return "prgprjselectmenus/update";
        }
        uiModel.asMap().clear();
        prgPrjSelectMenuService.updatePrgPrjSelectMenu(prgPrjSelectMenu);
        return "redirect:/prgprjselectmenus/" + encodeUrlPathSegment(prgPrjSelectMenu.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String PrgPrjSelectMenuController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, prgPrjSelectMenuService.findPrgPrjSelectMenu(id));
        return "prgprjselectmenus/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String PrgPrjSelectMenuController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        PrgPrjSelectMenu prgPrjSelectMenu = prgPrjSelectMenuService.findPrgPrjSelectMenu(id);
        prgPrjSelectMenuService.deletePrgPrjSelectMenu(prgPrjSelectMenu);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/prgprjselectmenus";
    }
    
    void PrgPrjSelectMenuController.populateEditForm(Model uiModel, PrgPrjSelectMenu prgPrjSelectMenu) {
        uiModel.addAttribute("prgPrjSelectMenu", prgPrjSelectMenu);
        uiModel.addAttribute("programs", programService.findAllPrograms());
        uiModel.addAttribute("projects", projectService.findAllProjects());
    }
    
    String PrgPrjSelectMenuController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
