// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.web;

import com.hpe.ao.domain.framework.TransactionLog;
import com.hpe.ao.reference.LogType;
import com.hpe.ao.service.TransactionLogService;
import com.hpe.ao.web.TransactionLogController;
import java.io.UnsupportedEncodingException;
import java.util.Arrays;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect TransactionLogController_Roo_Controller {
    
    @Autowired
    TransactionLogService TransactionLogController.transactionLogService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String TransactionLogController.create(@Valid TransactionLog transactionLog, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, transactionLog);
            return "transactionlogs/create";
        }
        uiModel.asMap().clear();
        transactionLogService.saveTransactionLog(transactionLog);
        return "redirect:/transactionlogs/" + encodeUrlPathSegment(transactionLog.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String TransactionLogController.createForm(Model uiModel) {
        populateEditForm(uiModel, new TransactionLog());
        return "transactionlogs/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String TransactionLogController.show(@PathVariable("id") Long id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("transactionlog", transactionLogService.findTransactionLog(id));
        uiModel.addAttribute("itemId", id);
        return "transactionlogs/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String TransactionLogController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("transactionlogs", TransactionLog.findTransactionLogEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) transactionLogService.countAllTransactionLogs() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("transactionlogs", TransactionLog.findAllTransactionLogs(sortFieldName, sortOrder));
        }
        addDateTimeFormatPatterns(uiModel);
        return "transactionlogs/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String TransactionLogController.update(@Valid TransactionLog transactionLog, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, transactionLog);
            return "transactionlogs/update";
        }
        uiModel.asMap().clear();
        transactionLogService.updateTransactionLog(transactionLog);
        return "redirect:/transactionlogs/" + encodeUrlPathSegment(transactionLog.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String TransactionLogController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, transactionLogService.findTransactionLog(id));
        return "transactionlogs/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String TransactionLogController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        TransactionLog transactionLog = transactionLogService.findTransactionLog(id);
        transactionLogService.deleteTransactionLog(transactionLog);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/transactionlogs";
    }
    
    void TransactionLogController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("transactionLog_logtimestamp_date_format", "yyyy-MM-dd HH:mm:ss");
    }
    
    void TransactionLogController.populateEditForm(Model uiModel, TransactionLog transactionLog) {
        uiModel.addAttribute("transactionLog", transactionLog);
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("logtypes", Arrays.asList(LogType.values()));
    }
    
    String TransactionLogController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
