// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.framework;

import com.hpe.ao.domain.framework.TransactionLogDataOnDemand;
import com.hpe.ao.domain.framework.TransactionLogIntegrationTest;
import com.hpe.ao.service.TransactionLogService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TransactionLogIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TransactionLogIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TransactionLogIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TransactionLogIntegrationTest: @Transactional;
    
    @Autowired
    TransactionLogDataOnDemand TransactionLogIntegrationTest.dod;
    
    @Autowired
    TransactionLogService TransactionLogIntegrationTest.transactionLogService;
    
    @Test
    public void TransactionLogIntegrationTest.testCountAllTransactionLogs() {
        Assert.assertNotNull("Data on demand for 'TransactionLog' failed to initialize correctly", dod.getRandomTransactionLog());
        long count = transactionLogService.countAllTransactionLogs();
        Assert.assertTrue("Counter for 'TransactionLog' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TransactionLogIntegrationTest.testFindTransactionLog() {
        TransactionLog obj = dod.getRandomTransactionLog();
        Assert.assertNotNull("Data on demand for 'TransactionLog' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TransactionLog' failed to provide an identifier", id);
        obj = transactionLogService.findTransactionLog(id);
        Assert.assertNotNull("Find method for 'TransactionLog' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TransactionLog' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TransactionLogIntegrationTest.testFindAllTransactionLogs() {
        Assert.assertNotNull("Data on demand for 'TransactionLog' failed to initialize correctly", dod.getRandomTransactionLog());
        long count = transactionLogService.countAllTransactionLogs();
        Assert.assertTrue("Too expensive to perform a find all test for 'TransactionLog', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TransactionLog> result = transactionLogService.findAllTransactionLogs();
        Assert.assertNotNull("Find all method for 'TransactionLog' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TransactionLog' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TransactionLogIntegrationTest.testFindTransactionLogEntries() {
        Assert.assertNotNull("Data on demand for 'TransactionLog' failed to initialize correctly", dod.getRandomTransactionLog());
        long count = transactionLogService.countAllTransactionLogs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TransactionLog> result = transactionLogService.findTransactionLogEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TransactionLog' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TransactionLog' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TransactionLogIntegrationTest.testFlush() {
        TransactionLog obj = dod.getRandomTransactionLog();
        Assert.assertNotNull("Data on demand for 'TransactionLog' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TransactionLog' failed to provide an identifier", id);
        obj = transactionLogService.findTransactionLog(id);
        Assert.assertNotNull("Find method for 'TransactionLog' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTransactionLog(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TransactionLog' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TransactionLogIntegrationTest.testUpdateTransactionLogUpdate() {
        TransactionLog obj = dod.getRandomTransactionLog();
        Assert.assertNotNull("Data on demand for 'TransactionLog' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TransactionLog' failed to provide an identifier", id);
        obj = transactionLogService.findTransactionLog(id);
        boolean modified =  dod.modifyTransactionLog(obj);
        Integer currentVersion = obj.getVersion();
        TransactionLog merged = transactionLogService.updateTransactionLog(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TransactionLog' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TransactionLogIntegrationTest.testSaveTransactionLog() {
        Assert.assertNotNull("Data on demand for 'TransactionLog' failed to initialize correctly", dod.getRandomTransactionLog());
        TransactionLog obj = dod.getNewTransientTransactionLog(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TransactionLog' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TransactionLog' identifier to be null", obj.getId());
        try {
            transactionLogService.saveTransactionLog(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'TransactionLog' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TransactionLogIntegrationTest.testDeleteTransactionLog() {
        TransactionLog obj = dod.getRandomTransactionLog();
        Assert.assertNotNull("Data on demand for 'TransactionLog' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TransactionLog' failed to provide an identifier", id);
        obj = transactionLogService.findTransactionLog(id);
        transactionLogService.deleteTransactionLog(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'TransactionLog' with identifier '" + id + "'", transactionLogService.findTransactionLog(id));
    }
    
}
