// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.base;

import com.hpe.ao.domain.base.AbstractEntity;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AbstractEntity_Roo_Configurable {
    
    declare @type: AbstractEntity: @Configurable;
    
}
