// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.base;

import com.hpe.ao.domain.base.BaseEffectiveDatedEntity;
import javax.persistence.MappedSuperclass;

privileged aspect BaseEffectiveDatedEntity_Roo_Jpa_Entity {
    
    declare @type: BaseEffectiveDatedEntity: @MappedSuperclass;
    
}
