// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.base;

import com.hpe.ao.domain.base.BaseEffectiveDatedEntity;
import java.util.List;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BaseEffectiveDatedEntity_Roo_Jpa_ActiveRecord {
    
    public static final List<String> BaseEffectiveDatedEntity.fieldNames4OrderClauseFilter = java.util.Arrays.asList("effectiveDate");
    
    public static long BaseEffectiveDatedEntity.countBaseEffectiveDatedEntitys() {
        return entityManager().createQuery("SELECT COUNT(o) FROM BaseEffectiveDatedEntity o", Long.class).getSingleResult();
    }
    
    public static List<BaseEffectiveDatedEntity> BaseEffectiveDatedEntity.findAllBaseEffectiveDatedEntitys() {
        return entityManager().createQuery("SELECT o FROM BaseEffectiveDatedEntity o", BaseEffectiveDatedEntity.class).getResultList();
    }
    
    public static List<BaseEffectiveDatedEntity> BaseEffectiveDatedEntity.findAllBaseEffectiveDatedEntitys(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM BaseEffectiveDatedEntity o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, BaseEffectiveDatedEntity.class).getResultList();
    }
    
    public static BaseEffectiveDatedEntity BaseEffectiveDatedEntity.findBaseEffectiveDatedEntity(Long id) {
        if (id == null) return null;
        return entityManager().find(BaseEffectiveDatedEntity.class, id);
    }
    
    public static List<BaseEffectiveDatedEntity> BaseEffectiveDatedEntity.findBaseEffectiveDatedEntityEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM BaseEffectiveDatedEntity o", BaseEffectiveDatedEntity.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<BaseEffectiveDatedEntity> BaseEffectiveDatedEntity.findBaseEffectiveDatedEntityEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM BaseEffectiveDatedEntity o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, BaseEffectiveDatedEntity.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public BaseEffectiveDatedEntity BaseEffectiveDatedEntity.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        BaseEffectiveDatedEntity merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
