// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.base;

import com.hpe.ao.domain.base.BaseEffectiveDatedEntry;
import java.util.List;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BaseEffectiveDatedEntry_Roo_Jpa_ActiveRecord {
    
    public static final List<String> BaseEffectiveDatedEntry.fieldNames4OrderClauseFilter = java.util.Arrays.asList("effectiveDate", "entryComments");
    
    public static long BaseEffectiveDatedEntry.countBaseEffectiveDatedEntrys() {
        return entityManager().createQuery("SELECT COUNT(o) FROM BaseEffectiveDatedEntry o", Long.class).getSingleResult();
    }
    
    public static List<BaseEffectiveDatedEntry> BaseEffectiveDatedEntry.findAllBaseEffectiveDatedEntrys() {
        return entityManager().createQuery("SELECT o FROM BaseEffectiveDatedEntry o", BaseEffectiveDatedEntry.class).getResultList();
    }
    
    public static List<BaseEffectiveDatedEntry> BaseEffectiveDatedEntry.findAllBaseEffectiveDatedEntrys(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM BaseEffectiveDatedEntry o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, BaseEffectiveDatedEntry.class).getResultList();
    }
    
    public static BaseEffectiveDatedEntry BaseEffectiveDatedEntry.findBaseEffectiveDatedEntry(Long id) {
        if (id == null) return null;
        return entityManager().find(BaseEffectiveDatedEntry.class, id);
    }
    
    public static List<BaseEffectiveDatedEntry> BaseEffectiveDatedEntry.findBaseEffectiveDatedEntryEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM BaseEffectiveDatedEntry o", BaseEffectiveDatedEntry.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<BaseEffectiveDatedEntry> BaseEffectiveDatedEntry.findBaseEffectiveDatedEntryEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM BaseEffectiveDatedEntry o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, BaseEffectiveDatedEntry.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public BaseEffectiveDatedEntry BaseEffectiveDatedEntry.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        BaseEffectiveDatedEntry merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
