// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.base;

import com.hpe.ao.domain.base.BaseEffectiveDatedEntry;
import java.util.Date;

privileged aspect BaseEffectiveDatedEntry_Roo_JavaBean {
    
    public Date BaseEffectiveDatedEntry.getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void BaseEffectiveDatedEntry.setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    
    public String BaseEffectiveDatedEntry.getEntryComments() {
        return this.entryComments;
    }
    
    public void BaseEffectiveDatedEntry.setEntryComments(String entryComments) {
        this.entryComments = entryComments;
    }
    
}
