// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.base;

import com.hpe.ao.domain.base.BaseEffectiveDatedEntity;
import java.util.Date;

privileged aspect BaseEffectiveDatedEntity_Roo_JavaBean {
    
    public Date BaseEffectiveDatedEntity.getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void BaseEffectiveDatedEntity.setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    
}
