// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.base;

import com.hpe.ao.domain.base.BaseEntity;
import javax.persistence.MappedSuperclass;

privileged aspect BaseEntity_Roo_Jpa_Entity {
    
    declare @type: BaseEntity: @MappedSuperclass;
    
}
