// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.base;

import com.hpe.ao.domain.base.BaseScheduleEntity;
import java.util.List;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BaseScheduleEntity_Roo_Jpa_ActiveRecord {
    
    public static final List<String> BaseScheduleEntity.fieldNames4OrderClauseFilter = java.util.Arrays.asList("startDateBaseline", "endDateBaseline", "startDateActual", "endDateActual");
    
    public static long BaseScheduleEntity.countBaseScheduleEntitys() {
        return entityManager().createQuery("SELECT COUNT(o) FROM BaseScheduleEntity o", Long.class).getSingleResult();
    }
    
    public static List<BaseScheduleEntity> BaseScheduleEntity.findAllBaseScheduleEntitys() {
        return entityManager().createQuery("SELECT o FROM BaseScheduleEntity o", BaseScheduleEntity.class).getResultList();
    }
    
    public static List<BaseScheduleEntity> BaseScheduleEntity.findAllBaseScheduleEntitys(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM BaseScheduleEntity o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, BaseScheduleEntity.class).getResultList();
    }
    
    public static BaseScheduleEntity BaseScheduleEntity.findBaseScheduleEntity(Long id) {
        if (id == null) return null;
        return entityManager().find(BaseScheduleEntity.class, id);
    }
    
    public static List<BaseScheduleEntity> BaseScheduleEntity.findBaseScheduleEntityEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM BaseScheduleEntity o", BaseScheduleEntity.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<BaseScheduleEntity> BaseScheduleEntity.findBaseScheduleEntityEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM BaseScheduleEntity o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, BaseScheduleEntity.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public BaseScheduleEntity BaseScheduleEntity.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        BaseScheduleEntity merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
