// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.base;

import com.hpe.ao.domain.base.BaseTaggedEntity;
import com.hpe.ao.domain.framework.Tag;
import com.hpe.ao.reference.Status;
import java.util.Set;

privileged aspect BaseTaggedEntity_Roo_JavaBean {
    
    public Set<Tag> BaseTaggedEntity.getTag() {
        return this.tag;
    }
    
    public void BaseTaggedEntity.setTag(Set<Tag> tag) {
        this.tag = tag;
    }
    
    public Status BaseTaggedEntity.getStatus() {
        return this.status;
    }
    
    public void BaseTaggedEntity.setStatus(Status status) {
        this.status = status;
    }
    
}
