// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.base;

import com.hpe.ao.domain.base.BaseEntity;

privileged aspect BaseEntity_Roo_JavaBean {
    
    public String BaseEntity.getName() {
        return this.name;
    }
    
    public void BaseEntity.setName(String name) {
        this.name = name;
    }
    
    public String BaseEntity.getDescription() {
        return this.description;
    }
    
    public void BaseEntity.setDescription(String description) {
        this.description = description;
    }
    
}
