// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.base;

import com.hpe.ao.domain.base.BaseScheduleEntity;
import java.util.Date;

privileged aspect BaseScheduleEntity_Roo_JavaBean {
    
    public Date BaseScheduleEntity.getStartDateBaseline() {
        return this.startDateBaseline;
    }
    
    public void BaseScheduleEntity.setStartDateBaseline(Date startDateBaseline) {
        this.startDateBaseline = startDateBaseline;
    }
    
    public Date BaseScheduleEntity.getEndDateBaseline() {
        return this.endDateBaseline;
    }
    
    public void BaseScheduleEntity.setEndDateBaseline(Date endDateBaseline) {
        this.endDateBaseline = endDateBaseline;
    }
    
    public Date BaseScheduleEntity.getStartDateActual() {
        return this.startDateActual;
    }
    
    public void BaseScheduleEntity.setStartDateActual(Date startDateActual) {
        this.startDateActual = startDateActual;
    }
    
    public Date BaseScheduleEntity.getEndDateActual() {
        return this.endDateActual;
    }
    
    public void BaseScheduleEntity.setEndDateActual(Date endDateActual) {
        this.endDateActual = endDateActual;
    }
    
}
