// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.base;

import com.hpe.ao.domain.base.BaseTaggedEntity;
import java.util.List;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BaseTaggedEntity_Roo_Jpa_ActiveRecord {
    
    public static final List<String> BaseTaggedEntity.fieldNames4OrderClauseFilter = java.util.Arrays.asList("tag", "status");
    
    public static long BaseTaggedEntity.countBaseTaggedEntitys() {
        return entityManager().createQuery("SELECT COUNT(o) FROM BaseTaggedEntity o", Long.class).getSingleResult();
    }
    
    public static List<BaseTaggedEntity> BaseTaggedEntity.findAllBaseTaggedEntitys() {
        return entityManager().createQuery("SELECT o FROM BaseTaggedEntity o", BaseTaggedEntity.class).getResultList();
    }
    
    public static List<BaseTaggedEntity> BaseTaggedEntity.findAllBaseTaggedEntitys(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM BaseTaggedEntity o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, BaseTaggedEntity.class).getResultList();
    }
    
    public static BaseTaggedEntity BaseTaggedEntity.findBaseTaggedEntity(Long id) {
        if (id == null) return null;
        return entityManager().find(BaseTaggedEntity.class, id);
    }
    
    public static List<BaseTaggedEntity> BaseTaggedEntity.findBaseTaggedEntityEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM BaseTaggedEntity o", BaseTaggedEntity.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<BaseTaggedEntity> BaseTaggedEntity.findBaseTaggedEntityEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM BaseTaggedEntity o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, BaseTaggedEntity.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public BaseTaggedEntity BaseTaggedEntity.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        BaseTaggedEntity merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
