// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.bean;

import com.hpe.ao.bean.SessionCache;
import com.hpe.ao.domain.transaction.Program;
import com.hpe.ao.domain.transaction.Project;

privileged aspect SessionCache_Roo_JavaBean {
    
    public Program SessionCache.getProgram() {
        return this.program;
    }
    
    public void SessionCache.setProgram(Program program) {
        this.program = program;
    }
    
    public Project SessionCache.getProject() {
        return this.project;
    }
    
    public void SessionCache.setProject(Project project) {
        this.project = project;
    }
    
    public Long SessionCache.getProjectId() {
        return this.projectId;
    }
    
    public void SessionCache.setProjectId(Long projectId) {
        this.projectId = projectId;
    }
    
    public Long SessionCache.getProgramId() {
        return this.programId;
    }
    
    public void SessionCache.setProgramId(Long programId) {
        this.programId = programId;
    }
    
}
