// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.framework;

import com.hpe.ao.domain.framework.Tag;
import java.util.List;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tag_Roo_Jpa_ActiveRecord {
    
    public static final List<String> Tag.fieldNames4OrderClauseFilter = java.util.Arrays.asList("type", "category");
    
    public static long Tag.countTags() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tag o", Long.class).getSingleResult();
    }
    
    public static List<Tag> Tag.findAllTags() {
        return entityManager().createQuery("SELECT o FROM Tag o", Tag.class).getResultList();
    }
    
    public static List<Tag> Tag.findAllTags(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Tag o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Tag.class).getResultList();
    }
    
    public static Tag Tag.findTag(Long id) {
        if (id == null) return null;
        return entityManager().find(Tag.class, id);
    }
    
    public static List<Tag> Tag.findTagEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tag o", Tag.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<Tag> Tag.findTagEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Tag o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Tag.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public Tag Tag.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tag merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
