// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.framework;

import com.hpe.ao.domain.framework.Tag;

privileged aspect Tag_Roo_JavaBean {
    
    public String Tag.getType() {
        return this.type;
    }
    
    public void Tag.setType(String type) {
        this.type = type;
    }
    
    public String Tag.getCategory() {
        return this.category;
    }
    
    public void Tag.setCategory(String category) {
        this.category = category;
    }
    
}
