// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.framework;

import com.hpe.ao.domain.framework.TransactionLog;
import com.hpe.ao.reference.LogType;
import java.util.Date;

privileged aspect TransactionLog_Roo_JavaBean {
    
    public String TransactionLog.getEntityName() {
        return this.entityName;
    }
    
    public void TransactionLog.setEntityName(String entityName) {
        this.entityName = entityName;
    }
    
    public Long TransactionLog.getEntiyKey1() {
        return this.entiyKey1;
    }
    
    public void TransactionLog.setEntiyKey1(Long entiyKey1) {
        this.entiyKey1 = entiyKey1;
    }
    
    public Long TransactionLog.getEntityKey2() {
        return this.entityKey2;
    }
    
    public void TransactionLog.setEntityKey2(Long entityKey2) {
        this.entityKey2 = entityKey2;
    }
    
    public LogType TransactionLog.getLogType() {
        return this.logType;
    }
    
    public void TransactionLog.setLogType(LogType logType) {
        this.logType = logType;
    }
    
    public String TransactionLog.getLogUser() {
        return this.logUser;
    }
    
    public void TransactionLog.setLogUser(String logUser) {
        this.logUser = logUser;
    }
    
    public Date TransactionLog.getLogTimestamp() {
        return this.logTimestamp;
    }
    
    public void TransactionLog.setLogTimestamp(Date logTimestamp) {
        this.logTimestamp = logTimestamp;
    }
    
    public String TransactionLog.getLogData() {
        return this.logData;
    }
    
    public void TransactionLog.setLogData(String logData) {
        this.logData = logData;
    }
    
}
