// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.framework;

import com.hpe.ao.domain.framework.TransactionLog;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TransactionLog_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager TransactionLog.entityManager;
    
    public static final List<String> TransactionLog.fieldNames4OrderClauseFilter = java.util.Arrays.asList("entityName", "entiyKey1", "entityKey2", "logType", "logUser", "logTimestamp", "logData");
    
    public static final EntityManager TransactionLog.entityManager() {
        EntityManager em = new TransactionLog().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long TransactionLog.countTransactionLogs() {
        return entityManager().createQuery("SELECT COUNT(o) FROM TransactionLog o", Long.class).getSingleResult();
    }
    
    public static List<TransactionLog> TransactionLog.findAllTransactionLogs() {
        return entityManager().createQuery("SELECT o FROM TransactionLog o", TransactionLog.class).getResultList();
    }
    
    public static List<TransactionLog> TransactionLog.findAllTransactionLogs(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM TransactionLog o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, TransactionLog.class).getResultList();
    }
    
    public static TransactionLog TransactionLog.findTransactionLog(Long id) {
        if (id == null) return null;
        return entityManager().find(TransactionLog.class, id);
    }
    
    public static List<TransactionLog> TransactionLog.findTransactionLogEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM TransactionLog o", TransactionLog.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<TransactionLog> TransactionLog.findTransactionLogEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM TransactionLog o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, TransactionLog.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void TransactionLog.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void TransactionLog.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            TransactionLog attached = TransactionLog.findTransactionLog(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void TransactionLog.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void TransactionLog.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public TransactionLog TransactionLog.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        TransactionLog merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
