// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hpe.ao.domain.framework;

import com.hpe.ao.domain.framework.TransactionLog;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TransactionLog_Roo_Configurable {
    
    declare @type: TransactionLog: @Configurable;
    
}
